In [22]:
import pandas as pd
import random
import os
import numpy as np
from sklearn.model_selection import train_test_split

In [31]:
frames = [
#     df_96, df_97, df_98, df_99, df_00,
#     df_01, df_02, df_03, df_04, df_05,
#     df_06, 
#     df_07, df_08, df_09, df_10,
#     df_11, 
    df_12, 
    df_13, df_14, 
#     df_15, df_16, df_17
]

In [61]:
# The data to load
# df_96 = "CollegeScorecard_Raw_Data/MERGED1996_97_PP.csv"
# df_97 = "CollegeScorecard_Raw_Data/MERGED1997_98_PP.csv"
# df_98 = "CollegeScorecard_Raw_Data/MERGED1998_99_PP.csv"
# df_99 = "CollegeScorecard_Raw_Data/MERGED1999_00_PP.csv"
# df_00 = "CollegeScorecard_Raw_Data/MERGED2000_01_PP.csv"
# df_01 = "CollegeScorecard_Raw_Data/MERGED2001_02_PP.csv"
# df_02 = "CollegeScorecard_Raw_Data/MERGED2002_03_PP.csv"
# df_03 = "CollegeScorecard_Raw_Data/MERGED2003_04_PP.csv"
# df_04 = "CollegeScorecard_Raw_Data/MERGED2004_05_PP.csv"
# df_05 = "CollegeScorecard_Raw_Data/MERGED2005_06_PP.csv"
# df_06 = "CollegeScorecard_Raw_Data/MERGED2006_07_PP.csv"
# df_07 = "CollegeScorecard_Raw_Data/MERGED2007_08_PP.csv"
# df_08 = "CollegeScorecard_Raw_Data/MERGED2008_09_PP.csv"
# df_09 = "CollegeScorecard_Raw_Data/MERGED2009_10_PP.csv"
# df_10 = "CollegeScorecard_Raw_Data/MERGED2010_11_PP.csv"
# df_11 = "CollegeScorecard_Raw_Data/MERGED2011_12_PP.csv"
df_12 = "CollegeScorecard_Raw_Data/MERGED2012_13_PP.csv"
df_13 = "CollegeScorecard_Raw_Data/MERGED2013_14_PP.csv"
df_14 = "CollegeScorecard_Raw_Data/MERGED2014_15_PP.csv"
# df_15 = "CollegeScorecard_Raw_Data/MERGED2015_16_PP.csv"
# df_16 = "CollegeScorecard_Raw_Data/MERGED2016_17_PP.csv"
# df_17 = "CollegeScorecard_Raw_Data/MERGED2017_18_PP.csv"

In [71]:
# college data dictionary
"""
Had to give a full path to avoid permission problem
"""
collegeDict= pd.read_excel('C:/Users/minji/OneDrive/Documents/2019Fall/SML/Project/jupyter/DS-5220-Project/CollegeScorecard_Raw_Data/CollegeScorecardDataDictionary.xlsx', sheet_name='data_dictionary')

In [75]:
collegeDict[collegeDict['dev-category']=='earnings']

,NAME OF DATA ELEMENT,dev-category,developer-friendly name,API data type,VARIABLE NAME,VALUE,LABEL,SOURCE,NOTES
1845,Count of students in the earnings cohort,earnings,student_count,integer,COUNT_ED,NaN,NaN,Treasury,This data element is no longer provided (all v...
1878,Number of students not working and not enrolle...,earnings,10_yrs_after_entry.not_working_not_enrolled.ov...,integer,COUNT_NWNE_P10,NaN,NaN,Treasury,NaN
1879,Number of students working and not enrolled 10...,earnings,10_yrs_after_entry.working_not_enrolled.overall,integer,COUNT_WNE_P10,NaN,NaN,Treasury,NaN
1880,Mean earnings of students working and not enro...,earnings,10_yrs_after_entry.working_not_enrolled.mean_e...,integer,MN_EARN_WNE_P10,NaN,NaN,Treasury,NaN
1881,Median earnings of students working and not en...,earnings,10_yrs_after_entry.median,integer,MD_EARN_WNE_P10,NaN,NaN,Treasury,Shown/used on consumer website.
1882,10th percentile of earnings of students workin...,earnings,10_yrs_after_entry.working_not_enrolled.earnin...,integer,PCT10_EARN_WNE_P10,NaN,NaN,Treasury,NaN
1883,25th percentile of earnings of students workin...,earnings,10_yrs_after_entry.working_not_enrolled.earnin...,integer,PCT25_EARN_WNE_P10,NaN,NaN,Treasury,NaN
1884,75th percentile of earnings of students workin...,earnings,10_yrs_after_entry.working_not_enrolled.earnin...,integer,PCT75_EARN_WNE_P10,NaN,NaN,Treasury,NaN
1885,90th percentile of earnings of students workin...,earnings,10_yrs_after_entry.working_not_enrolled.earnin...,integer,PCT90_EARN_WNE_P10,NaN,NaN,Treasury,NaN
1886,Standard deviation of earnings of students wor...,earnings,10_yrs_after_entry.working_not_enrolled.std_dev,integer,SD_EARN_WNE_P10,NaN,NaN,Treasury,NaN
1887,Number of students working and not enrolled 10...,earnings,10_yrs_after_entry.working_not_enrolled.income...,integer,COUNT_WNE_INC1_P10,NaN,NaN,Treasury,NaN
1888,Number of students working and not enrolled 10...,earnings,10_yrs_after_entry.working_not_enrolled.income...,integer,COUNT_WNE_INC2_P10,NaN,NaN,Treasury,NaN
1889,Number of students working and not enrolled 10...,earnings,10_yrs_after_entry.working_not_enrolled.income...,integer,COUNT_WNE_INC3_P10,NaN,NaN,Treasury,NaN
1890,Number of dependent students working and not e...,earnings,10_yrs_after_entry.working_not_enrolled.depend...,integer,COUNT_WNE_INDEP0_INC1_P10,NaN,NaN,Treasury,NaN
1891,Number of dependent students working and not e...,earnings,10_yrs_after_entry.working_not_enrolled.depend...,integer,COUNT_WNE_INDEP0_P10,NaN,NaN,Treasury,NaN
1892,Number of independent students working and not...,earnings,10_yrs_after_entry.independent_students,integer,COUNT_WNE_INDEP1_P10,NaN,NaN,Treasury,NaN
1893,Number of female students working and not enro...,earnings,10_yrs_after_entry.female_students,integer,COUNT_WNE_MALE0_P10,NaN,NaN,Treasury,NaN
1894,Number of male students working and not enroll...,earnings,10_yrs_after_entry.male_students,integer,COUNT_WNE_MALE1_P10,NaN,NaN,Treasury,NaN
1895,"Share of students earning over $25,000/year (t...",earnings,10_yrs_after_entry.percent_greater_than_25000,float,GT_25K_P10,NaN,NaN,Treasury,NaN
1896,"Share of students earning over $28,000/year (t...",earnings,10_yrs_after_entry.percent_greater_than_28000,float,GT_28K_P10,NaN,NaN,Treasury,NaN
1897,Mean earnings of students working and not enro...,earnings,10_yrs_after_entry.mean_earnings.lowest_tercile,integer,MN_EARN_WNE_INC1_P10,NaN,NaN,Treasury,NaN
1898,Mean earnings of students working and not enro...,earnings,10_yrs_after_entry.mean_earnings.middle_tercile,integer,MN_EARN_WNE_INC2_P10,NaN,NaN,Treasury,NaN
1899,Mean earnings of students working and not enro...,earnings,10_yrs_after_entry.mean_earnings.highest_tercile,integer,MN_EARN_WNE_INC3_P10,NaN,NaN,Treasury,NaN
1900,Mean earnings of dependent students working an...,earnings,10_yrs_after_entry.mean_earnings.dependent_stu...,integer,MN_EARN_WNE_INDEP0_INC1_P10,NaN,NaN,Treasury,NaN
1901,Mean earnings of dependent students working an...,earnings,10_yrs_after_entry.mean_earnings.dependent_stu...,integer,MN_EARN_WNE_INDEP0_P10,NaN,NaN,Treasury,NaN
1902,Mean earnings of independent students working ...,earnings,10_yrs_after_entry.mean_earnings.independent_s...,integer,MN_EARN_WNE_INDEP1_P10,NaN,NaN,Treasury,NaN
1903,Mean earnings of female students working and n...,earnings,10_yrs_after_entry.mean_earnings.female_students,integer,MN_EARN_WNE_MALE0_P10,NaN,NaN,Treasury,NaN
1904,Mean earnings of male students working and not...,earnings,10_yrs_after_entry.mean_earnings.male_students,integer,MN_EARN_WNE_MALE1_P10,NaN,NaN,Treasury,NaN
1905,Number of students not working and not enrolle...,earnings,6_yrs_after_entry.not_working_not_enrolled.ove...,integer,COUNT_NWNE_P6,NaN,NaN,Treasury,NaN
1906,Number of students working and not enrolled 6 ...,earnings,6_yrs_after_entry.working_not_enrolled.overall,integer,COUNT_WNE_P6,NaN,NaN,Treasury,NaN
...,...,...,...,...,...,...,...,...,...
1923,"Share of students earning over $28,000/year (t...",earnings,6_yrs_after_entry.percent_greater_than_28000,float,GT_28K_P6,NaN,NaN,Treasury,NaN
1924,Mean earnings of students working and not enro...,earnings,6_yrs_after_entry.mean_earnings.lowest_tercile,float,MN_EARN_WNE_INC1_P6,NaN,NaN,Treasury,NaN
1925,Mean earnings of students working and not enro...,earnings,6_yrs_after_entry.mean_earnings.middle_tercile,float,MN_EARN_WNE_INC2_P6,NaN,NaN,Treasury,NaN
1926,Mean earnings of students working and not enro...,earnings,6_yrs_after_entry.mean_earnings.highest_tercile,float,MN_EARN_WNE_INC3_P6,NaN,NaN,Treasury,NaN
1927,Mean earnings of dependent students working an...,earnings,6_yrs_after_entry.mean_earnings.dependent_stud...,float,MN_EARN_WNE_INDEP0_INC1_P6,NaN,NaN,Treasury,NaN
1928,Mean earnings of dependent students working an...,earnings,6_yrs_after_entry.mean_earnings.dependent_stud...,float,MN_EARN_WNE_INDEP0_P6,NaN,NaN,Treasury,NaN
1929,Mean earnings of independent students working ...,earnings,6_yrs_after_entry.mean_earnings.independent_st...,float,MN_EARN_WNE_INDEP1_P6,NaN,NaN,Treasury,NaN
1930,Mean earnings of female students working and n...,earnings,6_yrs_after_entry.mean_earnings.female_students,float,MN_EARN_WNE_MALE0_P6,NaN,NaN,Treasury,NaN
1931,Mean earnings of male students working and not...,earnings,6_yrs_after_entry.mean_earnings.male_students,float,MN_EARN_WNE_MALE1_P6,NaN,NaN,Treasury,NaN
1932,Number of students not working and not enrolle...,earnings,7_yrs_after_entry.not_working_not_enrolled,float,COUNT_NWNE_P7,NaN,NaN,Treasury,NaN
1933,Number of students working and not enrolled 7 ...,earnings,7_yrs_after_entry.working_not_enrolled,integer,COUNT_WNE_P7,NaN,NaN,Treasury,NaN
1934,Mean earnings of students working and not enro...,earnings,7_yrs_after_entry.mean_earnings,float,MN_EARN_WNE_P7,NaN,NaN,Treasury,NaN
1935,Standard deviation of earnings of students wor...,earnings,7_yrs_after_entry.std_dev,float,SD_EARN_WNE_P7,NaN,NaN,Treasury,NaN
1936,"Share of students earning over $25,000/year (t...",earnings,7_yrs_after_entry.percent_greater_than_25000,float,GT_25K_P7,NaN,NaN,Treasury,NaN
1937,Number of students not working and not enrolle...,earnings,8_yrs_after_entry.not_working_not_enrolled,integer,COUNT_NWNE_P8,NaN,NaN,Treasury,NaN
1938,Number of students working and not enrolled 8 ...,earnings,8_yrs_after_entry.working_not_enrolled,integer,COUNT_WNE_P8,NaN,NaN,Treasury,NaN
1939,Mean earnings of students working and not enro...,earnings,8_yrs_after_entry.mean_earnings,float,MN_EARN_WNE_P8,NaN,NaN,Treasury,NaN
1940,Median earnings of students working and not en...,earnings,8_yrs_after_entry.median_earnings,float,MD_EARN_WNE_P8,NaN,NaN,Treasury,NaN
1941,10th percentile of earnings of students workin...,earnings,8_yrs_after_entry.10th_percentile_earnings,integer,PCT10_EARN_WNE_P8,NaN,NaN,Treasury,NaN
1942,25th percentile of earnings of students workin...,earnings,8_yrs_after_entry.25th_percentile_earnings,integer,PCT25_EARN_WNE_P8,NaN,NaN,Treasury,NaN
1943,75th percentile of earnings of students workin...,earnings,8_yrs_after_entry.75th_percentile_earnings,integer,PCT75_EARN_WNE_P8,NaN,NaN,Treasury,NaN
1944,90th percentile of earnings of students workin...,earnings,8_yrs_after_entry.90th_percentile_earnings,integer,PCT90_EARN_WNE_P8,NaN,NaN,Treasury,NaN
1945,Standard deviation of earnings of students wor...,earnings,8_yrs_after_entry.std_deviation,float,SD_EARN_WNE_P8,NaN,NaN,Treasury,NaN
1946,"Share of students earning over $25,000/year (t...",earnings,8_yrs_after_entry.percent_greater_than_25000,float,GT_25K_P8,NaN,NaN,Treasury,NaN
1947,"Share of students earning over $28,000/year (t...",earnings,8_yrs_after_entry.percent_greater_than_28000,float,GT_28K_P8,NaN,NaN,Treasury,NaN
1948,Number of students not working and not enrolle...,earnings,9_yrs_after_entry.not_working_not_enrolled,integer,COUNT_NWNE_P9,NaN,NaN,Treasury,NaN
1949,Number of students working and not enrolled 9 ...,earnings,9_yrs_after_entry.working_not_enrolled,integer,COUNT_WNE_P9,NaN,NaN,Treasury,NaN
1950,Mean earnings of students working and not enro...,earnings,9_yrs_after_entry.mean_earnings,float,MN_EARN_WNE_P9,NaN,NaN,Treasury,NaN
1951,Standard deviation of earnings of students wor...,earnings,9_yrs_after_entry.std_deviation,float,SD_EARN_WNE_P9,NaN,NaN,Treasury,NaN
1952,"Share of students earning over $25,000/year (t...",earnings,9_yrs_after_entry.percent_greater_than_25000,float,GT_25K_P9,NaN,NaN,Treasury,NaN

In [67]:
# Random selection !!! Need to do stratified sample for selecting data according to each state.
def fileRead(filename): 
    # Count the lines
    num_lines = sum(1 for l in open(filename))

    # Sample size - in this case ~10%
    size = int(num_lines / 10)

    # The row indices to skip - make sure 0 is not included to keep the header!
    skip_idx = random.sample(range(1, num_lines), num_lines - size)

    # Read the data
    data = pd.read_csv(filename, skiprows=skip_idx)
    return data

In [15]:
# df_96 = fileRead(df_96)
# df_97 = fileRead(df_97)
# df_98 = fileRead(df_98)
# df_99 = fileRead(df_99)
# df_00 = fileRead(df_00)
# df_01 = fileRead(df_01)
# df_02 = fileRead(df_02)
# df_03 = fileRead(df_03)
# df_04 = fileRead(df_04)
# df_05 = fileRead(df_05)
# df_06 = fileRead(df_06)
# df_07 = fileRead(df_07)
# df_08 = fileRead(df_08)
# df_09 = fileRead(df_09)
# df_10 = fileRead(df_10)
# df_11 = fileRead(df_11)
df_12 = fileRead(df_12)
df_13 = fileRead(df_13)
df_14 = fileRead(df_14)
# df_15 = fileRead(df_15)
# df_16 = fileRead(df_16)
# df_17 = fileRead(df_17)

c:\users\minji\appdata\local\programs\python\python36-32\lib\site-packages\IPython\core\interactiveshell.py:2850: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

In [30]:
df_10.info() #

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Columns: 1977 entries, UNITID to OMENRUP_PARTTIME_POOLED_SUPP
dtypes: float64(813), int64(10), object(1154)
memory usage: 7.9+ MB

In [32]:
# add the dataframes of 2012, 13,14 years and save them into 'data'
data = pd.concat(frames)

In [42]:
# Replace privacysuppressed to nan. It's at DEATH_YR2_RT variable, Percent died within 2 years at original institution
data = data.replace('PrivacySuppressed', np.nan) 
print(data.shape)

(2326, 1977)

In [54]:
list(data.columns)

['UNITID',
 'INSTNM',
 'CITY',
 'ACCREDAGENCY',
 'SCH_DEG',
 'HCM2',
 'MAIN',
 'NUMBRANCH',
 'PREDDEG',
 'HIGHDEG',
 'CONTROL',
 'ST_FIPS',
 'REGION',
 'LOCALE',
 'LOCALE2',
 'CCBASIC',
 'CCUGPROF',
 'CCSIZSET',
 'HBCU',
 'PBI',
 'ANNHI',
 'TRIBAL',
 'AANAPII',
 'HSI',
 'NANTI',
 'MENONLY',
 'WOMENONLY',
 'RELAFFIL',
 'ADM_RATE',
 'ADM_RATE_ALL',
 'SATVR25',
 'SATVR75',
 'SATMT25',
 'SATMT75',
 'SATWR25',
 'SATWR75',
 'SATVRMID',
 'SATMTMID',
 'SATWRMID',
 'ACTCM25',
 'ACTCM75',
 'ACTEN25',
 'ACTEN75',
 'ACTMT25',
 'ACTMT75',
 'ACTWR25',
 'ACTWR75',
 'ACTCMMID',
 'ACTENMID',
 'ACTMTMID',
 'ACTWRMID',
 'SAT_AVG',
 'SAT_AVG_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'PCIP12',
 'PCIP13',
 'PCIP14',
 'PCIP15',
 'PCIP16',
 'PCIP19',
 'PCIP22',
 'PCIP23',
 'PCIP24',
 'PCIP25',
 'PCIP26',
 'PCIP27',
 'PCIP29',
 'PCIP30',
 'PCIP31',
 'PCIP38',
 'PCIP39',
 'PCIP40',
 'PCIP41',
 'PCIP42',
 'PCIP43',
 'PCIP44',
 'PCIP45',
 'PCIP46',
 'PCIP47',
 'PCIP48',
 'PCIP49',
 'PCIP50',
 'PCIP51',
 'PCIP52',
 'PCIP54',
 'CIP01CERT1',
 'CIP01CERT2',
 'CIP01ASSOC',
 'CIP01CERT4',
 'CIP01BACHL',
 'CIP03CERT1',
 'CIP03CERT2',
 'CIP03ASSOC',
 'CIP03CERT4',
 'CIP03BACHL',
 'CIP04CERT1',
 'CIP04CERT2',
 'CIP04ASSOC',
 'CIP04CERT4',
 'CIP04BACHL',
 'CIP05CERT1',
 'CIP05CERT2',
 'CIP05ASSOC',
 'CIP05CERT4',
 'CIP05BACHL',
 'CIP09CERT1',
 'CIP09CERT2',
 'CIP09ASSOC',
 'CIP09CERT4',
 'CIP09BACHL',
 'CIP10CERT1',
 'CIP10CERT2',
 'CIP10ASSOC',
 'CIP10CERT4',
 'CIP10BACHL',
 'CIP11CERT1',
 'CIP11CERT2',
 'CIP11ASSOC',
 'CIP11CERT4',
 'CIP11BACHL',
 'CIP12CERT1',
 'CIP12CERT2',
 'CIP12ASSOC',
 'CIP12CERT4',
 'CIP12BACHL',
 'CIP13CERT1',
 'CIP13CERT2',
 'CIP13ASSOC',
 'CIP13CERT4',
 'CIP13BACHL',
 'CIP14CERT1',
 'CIP14CERT2',
 'CIP14ASSOC',
 'CIP14CERT4',
 'CIP14BACHL',
 'CIP15CERT1',
 'CIP15CERT2',
 'CIP15ASSOC',
 'CIP15CERT4',
 'CIP15BACHL',
 'CIP16CERT1',
 'CIP16CERT2',
 'CIP16ASSOC',
 'CIP16CERT4',
 'CIP16BACHL',
 'CIP19CERT1',
 'CIP19CERT2',
 'CIP19ASSOC',
 'CIP19CERT4',
 'CIP19BACHL',
 'CIP22CERT1',
 'CIP22CERT2',
 'CIP22ASSOC',
 'CIP22CERT4',
 'CIP22BACHL',
 'CIP23CERT1',
 'CIP23CERT2',
 'CIP23ASSOC',
 'CIP23CERT4',
 'CIP23BACHL',
 'CIP24CERT1',
 'CIP24CERT2',
 'CIP24ASSOC',
 'CIP24CERT4',
 'CIP24BACHL',
 'CIP25CERT1',
 'CIP25CERT2',
 'CIP25ASSOC',
 'CIP25CERT4',
 'CIP25BACHL',
 'CIP26CERT1',
 'CIP26CERT2',
 'CIP26ASSOC',
 'CIP26CERT4',
 'CIP26BACHL',
 'CIP27CERT1',
 'CIP27CERT2',
 'CIP27ASSOC',
 'CIP27CERT4',
 'CIP27BACHL',
 'CIP29CERT1',
 'CIP29CERT2',
 'CIP29ASSOC',
 'CIP29CERT4',
 'CIP29BACHL',
 'CIP30CERT1',
 'CIP30CERT2',
 'CIP30ASSOC',
 'CIP30CERT4',
 'CIP30BACHL',
 'CIP31CERT1',
 'CIP31CERT2',
 'CIP31ASSOC',
 'CIP31CERT4',
 'CIP31BACHL',
 'CIP38CERT1',
 'CIP38CERT2',
 'CIP38ASSOC',
 'CIP38CERT4',
 'CIP38BACHL',
 'CIP39CERT1',
 'CIP39CERT2',
 'CIP39ASSOC',
 'CIP39CERT4',
 'CIP39BACHL',
 'CIP40CERT1',
 'CIP40CERT2',
 'CIP40ASSOC',
 'CIP40CERT4',
 'CIP40BACHL',
 'CIP41CERT1',
 'CIP41CERT2',
 'CIP41ASSOC',
 'CIP41CERT4',
 'CIP41BACHL',
 'CIP42CERT1',
 'CIP42CERT2',
 'CIP42ASSOC',
 'CIP42CERT4',
 'CIP42BACHL',
 'CIP43CERT1',
 'CIP43CERT2',
 'CIP43ASSOC',
 'CIP43CERT4',
 'CIP43BACHL',
 'CIP44CERT1',
 'CIP44CERT2',
 'CIP44ASSOC',
 'CIP44CERT4',
 'CIP44BACHL',
 'CIP45CERT1',
 'CIP45CERT2',
 'CIP45ASSOC',
 'CIP45CERT4',
 'CIP45BACHL',
 'CIP46CERT1',
 'CIP46CERT2',
 'CIP46ASSOC',
 'CIP46CERT4',
 'CIP46BACHL',
 'CIP47CERT1',
 'CIP47CERT2',
 'CIP47ASSOC',
 'CIP47CERT4',
 'CIP47BACHL',
 'CIP48CERT1',
 'CIP48CERT2',
 'CIP48ASSOC',
 'CIP48CERT4',
 'CIP48BACHL',
 'CIP49CERT1',
 'CIP49CERT2',
 'CIP49ASSOC',
 'CIP49CERT4',
 'CIP49BACHL',
 'CIP50CERT1',
 'CIP50CERT2',
 'CIP50ASSOC',
 'CIP50CERT4',
 'CIP50BACHL',
 'CIP51CERT1',
 'CIP51CERT2',
 'CIP51ASSOC',
 'CIP51CERT4',
 'CIP51BACHL',
 'CIP52CERT1',
 'CIP52CERT2',
 'CIP52ASSOC',
 'CIP52CERT4',
 'CIP52BACHL',
 'CIP54CERT1',
 'CIP54CERT2',
 'CIP54ASSOC',
 'CIP54CERT4',
 'CIP54BACHL',
 'DISTANCEONLY',
 'UGDS',
 'UG',
 'UGDS_WHITE',
 'UGDS_BLACK',
 'UGDS_HISP',
 'UGDS_ASIAN',
 'UGDS_AIAN',
 'UGDS_NHPI',
 'UGDS_2MOR',
 'UGDS_NRA',
 'UGDS_UNKN',
 'UGDS_WHITENH',
 'UGDS_BLACKNH',
 'UGDS_API',
 'UGDS_AIANOLD',
 'UGDS_HISPOLD',
 'UG_NRA',
 'UG_UNKN',
 'UG_WHITENH',
 'UG_BLACKNH',
 'UG_API',
 'UG_AIANOLD',
 'UG_HISPOLD',
 'PPTUG_EF',
 'PPTUG_EF2',
 'CURROPER',
 'NPT4_PUB',
 'NPT4_PRIV',
 'NPT4_PROG',
 'NPT4_OTHER',
 'NPT41_PUB',
 'NPT42_PUB',
 'NPT43_PUB',
 'NPT44_PUB',
 'NPT45_PUB',
 'NPT41_PRIV',
 'NPT42_PRIV',
 'NPT43_PRIV',
 'NPT44_PRIV',
 'NPT45_PRIV',
 'NPT41_PROG',
 'NPT42_PROG',
 'NPT43_PROG',
 'NPT44_PROG',
 'NPT45_PROG',
 'NPT41_OTHER',
 'NPT42_OTHER',
 'NPT43_OTHER',
 'NPT44_OTHER',
 'NPT45_OTHER',
 'NPT4_048_PUB',
 'NPT4_048_PRIV',
 'NPT4_048_PROG',
 'NPT4_048_OTHER',
 'NPT4_3075_PUB',
 'NPT4_3075_PRIV',
 'NPT4_75UP_PUB',
 'NPT4_75UP_PRIV',
 'NPT4_3075_PROG',
 'NPT4_3075_OTHER',
 'NPT4_75UP_PROG',
 'NPT4_75UP_OTHER',
 'NUM4_PUB',
 'NUM4_PRIV',
 'NUM4_PROG',
 'NUM4_OTHER',
 'NUM41_PUB',
 'NUM42_PUB',
 'NUM43_PUB',
 'NUM44_PUB',
 'NUM45_PUB',
 'NUM41_PRIV',
 'NUM42_PRIV',
 'NUM43_PRIV',
 'NUM44_PRIV',
 'NUM45_PRIV',
 'NUM41_PROG',
 'NUM42_PROG',
 'NUM43_PROG',
 'NUM44_PROG',
 'NUM45_PROG',
 'NUM41_OTHER',
 'NUM42_OTHER',
 'NUM43_OTHER',
 'NUM44_OTHER',
 'NUM45_OTHER',
 'COSTT4_A',
 'COSTT4_P',
 'TUITIONFEE_IN',
 'TUITIONFEE_OUT',
 'TUITIONFEE_PROG',
 'TUITFTE',
 'INEXPFTE',
 'AVGFACSAL',
 'PFTFAC',
 'PCTPELL',
 'C150_4',
 'C150_L4',
 'C150_4_POOLED',
 'C150_L4_POOLED',
 'POOLYRS',
 'PFTFTUG1_EF',
 'D150_4',
 'D150_L4',
 'D150_4_POOLED',
 'D150_L4_POOLED',
 'C150_4_WHITE',
 'C150_4_BLACK',
 'C150_4_HISP',
 'C150_4_ASIAN',
 'C150_4_AIAN',
 'C150_4_NHPI',
 'C150_4_2MOR',
 'C150_4_NRA',
 'C150_4_UNKN',
 'C150_4_WHITENH',
 'C150_4_BLACKNH',
 'C150_4_API',
 'C150_4_AIANOLD',
 'C150_4_HISPOLD',
 'C150_L4_WHITE',
 'C150_L4_BLACK',
 'C150_L4_HISP',
 'C150_L4_ASIAN',
 'C150_L4_AIAN',
 'C150_L4_NHPI',
 'C150_L4_2MOR',
 'C150_L4_NRA',
 'C150_L4_UNKN',
 'C150_L4_WHITENH',
 'C150_L4_BLACKNH',
 'C150_L4_API',
 'C150_L4_AIANOLD',
 'C150_L4_HISPOLD',
 'C200_4',
 'C200_L4',
 'D200_4',
 'D200_L4',
 'RET_FT4',
 'RET_FTL4',
 'RET_PT4',
 'RET_PTL4',
 'C200_4_POOLED',
 'C200_L4_POOLED',
 'POOLYRS200',
 'D200_4_POOLED',
 'D200_L4_POOLED',
 'PCTFLOAN',
 'UG25ABV',
 'CDR2',
 'CDR3',
 'DEATH_YR2_RT',
 'COMP_ORIG_YR2_RT',
 'COMP_4YR_TRANS_YR2_RT',
 'COMP_2YR_TRANS_YR2_RT',
 'WDRAW_ORIG_YR2_RT',
 'WDRAW_4YR_TRANS_YR2_RT',
 'WDRAW_2YR_TRANS_YR2_RT',
 'ENRL_ORIG_YR2_RT',
 'ENRL_4YR_TRANS_YR2_RT',
 'ENRL_2YR_TRANS_YR2_RT',
 'UNKN_ORIG_YR2_RT',
 'UNKN_4YR_TRANS_YR2_RT',
 'UNKN_2YR_TRANS_YR2_RT',
 'LO_INC_DEATH_YR2_RT',
 'LO_INC_COMP_ORIG_YR2_RT',
 'LO_INC_COMP_4YR_TRANS_YR2_RT',
 'LO_INC_COMP_2YR_TRANS_YR2_RT',
 'LO_INC_WDRAW_ORIG_YR2_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR2_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR2_RT',
 'LO_INC_ENRL_ORIG_YR2_RT',
 'LO_INC_ENRL_4YR_TRANS_YR2_RT',
 'LO_INC_ENRL_2YR_TRANS_YR2_RT',
 'LO_INC_UNKN_ORIG_YR2_RT',
 'LO_INC_UNKN_4YR_TRANS_YR2_RT',
 'LO_INC_UNKN_2YR_TRANS_YR2_RT',
 'MD_INC_DEATH_YR2_RT',
 'MD_INC_COMP_ORIG_YR2_RT',
 'MD_INC_COMP_4YR_TRANS_YR2_RT',
 'MD_INC_COMP_2YR_TRANS_YR2_RT',
 'MD_INC_WDRAW_ORIG_YR2_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR2_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR2_RT',
 'MD_INC_ENRL_ORIG_YR2_RT',
 'MD_INC_ENRL_4YR_TRANS_YR2_RT',
 'MD_INC_ENRL_2YR_TRANS_YR2_RT',
 'MD_INC_UNKN_ORIG_YR2_RT',
 'MD_INC_UNKN_4YR_TRANS_YR2_RT',
 'MD_INC_UNKN_2YR_TRANS_YR2_RT',
 'HI_INC_DEATH_YR2_RT',
 'HI_INC_COMP_ORIG_YR2_RT',
 'HI_INC_COMP_4YR_TRANS_YR2_RT',
 'HI_INC_COMP_2YR_TRANS_YR2_RT',
 'HI_INC_WDRAW_ORIG_YR2_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR2_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR2_RT',
 'HI_INC_ENRL_ORIG_YR2_RT',
 'HI_INC_ENRL_4YR_TRANS_YR2_RT',
 'HI_INC_ENRL_2YR_TRANS_YR2_RT',
 'HI_INC_UNKN_ORIG_YR2_RT',
 'HI_INC_UNKN_4YR_TRANS_YR2_RT',
 'HI_INC_UNKN_2YR_TRANS_YR2_RT',
 'DEP_DEATH_YR2_RT',
 'DEP_COMP_ORIG_YR2_RT',
 'DEP_COMP_4YR_TRANS_YR2_RT',
 'DEP_COMP_2YR_TRANS_YR2_RT',
 'DEP_WDRAW_ORIG_YR2_RT',
 'DEP_WDRAW_4YR_TRANS_YR2_RT',
 'DEP_WDRAW_2YR_TRANS_YR2_RT',
 'DEP_ENRL_ORIG_YR2_RT',
 'DEP_ENRL_4YR_TRANS_YR2_RT',
 'DEP_ENRL_2YR_TRANS_YR2_RT',
 'DEP_UNKN_ORIG_YR2_RT',
 'DEP_UNKN_4YR_TRANS_YR2_RT',
 'DEP_UNKN_2YR_TRANS_YR2_RT',
 'IND_DEATH_YR2_RT',
 'IND_COMP_ORIG_YR2_RT',
 'IND_COMP_4YR_TRANS_YR2_RT',
 'IND_COMP_2YR_TRANS_YR2_RT',
 'IND_WDRAW_ORIG_YR2_RT',
 'IND_WDRAW_4YR_TRANS_YR2_RT',
 'IND_WDRAW_2YR_TRANS_YR2_RT',
 'IND_ENRL_ORIG_YR2_RT',
 'IND_ENRL_4YR_TRANS_YR2_RT',
 'IND_ENRL_2YR_TRANS_YR2_RT',
 'IND_UNKN_ORIG_YR2_RT',
 'IND_UNKN_4YR_TRANS_YR2_RT',
 'IND_UNKN_2YR_TRANS_YR2_RT',
 'FEMALE_DEATH_YR2_RT',
 'FEMALE_COMP_ORIG_YR2_RT',
 'FEMALE_COMP_4YR_TRANS_YR2_RT',
 'FEMALE_COMP_2YR_TRANS_YR2_RT',
 'FEMALE_WDRAW_ORIG_YR2_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR2_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR2_RT',
 'FEMALE_ENRL_ORIG_YR2_RT',
 'FEMALE_ENRL_4YR_TRANS_YR2_RT',
 'FEMALE_ENRL_2YR_TRANS_YR2_RT',
 'FEMALE_UNKN_ORIG_YR2_RT',
 'FEMALE_UNKN_4YR_TRANS_YR2_RT',
 'FEMALE_UNKN_2YR_TRANS_YR2_RT',
 'MALE_DEATH_YR2_RT',
 'MALE_COMP_ORIG_YR2_RT',
 'MALE_COMP_4YR_TRANS_YR2_RT',
 'MALE_COMP_2YR_TRANS_YR2_RT',
 'MALE_WDRAW_ORIG_YR2_RT',
 'MALE_WDRAW_4YR_TRANS_YR2_RT',
 'MALE_WDRAW_2YR_TRANS_YR2_RT',
 'MALE_ENRL_ORIG_YR2_RT',
 'MALE_ENRL_4YR_TRANS_YR2_RT',
 'MALE_ENRL_2YR_TRANS_YR2_RT',
 'MALE_UNKN_ORIG_YR2_RT',
 'MALE_UNKN_4YR_TRANS_YR2_RT',
 'MALE_UNKN_2YR_TRANS_YR2_RT',
 'PELL_DEATH_YR2_RT',
 'PELL_COMP_ORIG_YR2_RT',
 'PELL_COMP_4YR_TRANS_YR2_RT',
 'PELL_COMP_2YR_TRANS_YR2_RT',
 'PELL_WDRAW_ORIG_YR2_RT',
 'PELL_WDRAW_4YR_TRANS_YR2_RT',
 'PELL_WDRAW_2YR_TRANS_YR2_RT',
 'PELL_ENRL_ORIG_YR2_RT',
 'PELL_ENRL_4YR_TRANS_YR2_RT',
 'PELL_ENRL_2YR_TRANS_YR2_RT',
 'PELL_UNKN_ORIG_YR2_RT',
 'PELL_UNKN_4YR_TRANS_YR2_RT',
 'PELL_UNKN_2YR_TRANS_YR2_RT',
 'NOPELL_DEATH_YR2_RT',
 'NOPELL_COMP_ORIG_YR2_RT',
 'NOPELL_COMP_4YR_TRANS_YR2_RT',
 'NOPELL_COMP_2YR_TRANS_YR2_RT',
 'NOPELL_WDRAW_ORIG_YR2_RT',
 'NOPELL_WDRAW_4YR_TRANS_YR2_RT',
 'NOPELL_WDRAW_2YR_TRANS_YR2_RT',
 'NOPELL_ENRL_ORIG_YR2_RT',
 'NOPELL_ENRL_4YR_TRANS_YR2_RT',
 'NOPELL_ENRL_2YR_TRANS_YR2_RT',
 'NOPELL_UNKN_ORIG_YR2_RT',
 'NOPELL_UNKN_4YR_TRANS_YR2_RT',
 'NOPELL_UNKN_2YR_TRANS_YR2_RT',
 'LOAN_DEATH_YR2_RT',
 'LOAN_COMP_ORIG_YR2_RT',
 'LOAN_COMP_4YR_TRANS_YR2_RT',
 'LOAN_COMP_2YR_TRANS_YR2_RT',
 'LOAN_WDRAW_ORIG_YR2_RT',
 'LOAN_WDRAW_4YR_TRANS_YR2_RT',
 'LOAN_WDRAW_2YR_TRANS_YR2_RT',
 'LOAN_ENRL_ORIG_YR2_RT',
 'LOAN_ENRL_4YR_TRANS_YR2_RT',
 'LOAN_ENRL_2YR_TRANS_YR2_RT',
 'LOAN_UNKN_ORIG_YR2_RT',
 'LOAN_UNKN_4YR_TRANS_YR2_RT',
 'LOAN_UNKN_2YR_TRANS_YR2_RT',
 'NOLOAN_DEATH_YR2_RT',
 'NOLOAN_COMP_ORIG_YR2_RT',
 'NOLOAN_COMP_4YR_TRANS_YR2_RT',
 'NOLOAN_COMP_2YR_TRANS_YR2_RT',
 'NOLOAN_WDRAW_ORIG_YR2_RT',
 'NOLOAN_WDRAW_4YR_TRANS_YR2_RT',
 'NOLOAN_WDRAW_2YR_TRANS_YR2_RT',
 'NOLOAN_ENRL_ORIG_YR2_RT',
 'NOLOAN_ENRL_4YR_TRANS_YR2_RT',
 'NOLOAN_ENRL_2YR_TRANS_YR2_RT',
 'NOLOAN_UNKN_ORIG_YR2_RT',
 'NOLOAN_UNKN_4YR_TRANS_YR2_RT',
 'NOLOAN_UNKN_2YR_TRANS_YR2_RT',
 'FIRSTGEN_DEATH_YR2_RT',
 'FIRSTGEN_COMP_ORIG_YR2_RT',
 'FIRSTGEN_COMP_4YR_TRANS_YR2_RT',
 'FIRSTGEN_COMP_2YR_TRANS_YR2_RT',
 'FIRSTGEN_WDRAW_ORIG_YR2_RT',
 'FIRSTGEN_WDRAW_4YR_TRANS_YR2_RT',
 'FIRSTGEN_WDRAW_2YR_TRANS_YR2_RT',
 'FIRSTGEN_ENRL_ORIG_YR2_RT',
 'FIRSTGEN_ENRL_4YR_TRANS_YR2_RT',
 'FIRSTGEN_ENRL_2YR_TRANS_YR2_RT',
 'FIRSTGEN_UNKN_ORIG_YR2_RT',
 'FIRSTGEN_UNKN_4YR_TRANS_YR2_RT',
 'FIRSTGEN_UNKN_2YR_TRANS_YR2_RT',
 'NOT1STGEN_DEATH_YR2_RT',
 'NOT1STGEN_COMP_ORIG_YR2_RT',
 'NOT1STGEN_COMP_4YR_TRANS_YR2_RT',
 'NOT1STGEN_COMP_2YR_TRANS_YR2_RT',
 'NOT1STGEN_WDRAW_ORIG_YR2_RT',
 'NOT1STGEN_WDRAW_4YR_TRANS_YR2_RT',
 'NOT1STGEN_WDRAW_2YR_TRANS_YR2_RT',
 'NOT1STGEN_ENRL_ORIG_YR2_RT',
 'NOT1STGEN_ENRL_4YR_TRANS_YR2_RT',
 'NOT1STGEN_ENRL_2YR_TRANS_YR2_RT',
 'NOT1STGEN_UNKN_ORIG_YR2_RT',
 'NOT1STGEN_UNKN_4YR_TRANS_YR2_RT',
 'NOT1STGEN_UNKN_2YR_TRANS_YR2_RT',
 'DEATH_YR3_RT',
 'COMP_ORIG_YR3_RT',
 'COMP_4YR_TRANS_YR3_RT',
 'COMP_2YR_TRANS_YR3_RT',
 'WDRAW_ORIG_YR3_RT',
 'WDRAW_4YR_TRANS_YR3_RT',
 'WDRAW_2YR_TRANS_YR3_RT',
 'ENRL_ORIG_YR3_RT',
 'ENRL_4YR_TRANS_YR3_RT',
 'ENRL_2YR_TRANS_YR3_RT',
 'UNKN_ORIG_YR3_RT',
 'UNKN_4YR_TRANS_YR3_RT',
 'UNKN_2YR_TRANS_YR3_RT',
 'LO_INC_DEATH_YR3_RT',
 'LO_INC_COMP_ORIG_YR3_RT',
 'LO_INC_COMP_4YR_TRANS_YR3_RT',
 'LO_INC_COMP_2YR_TRANS_YR3_RT',
 'LO_INC_WDRAW_ORIG_YR3_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR3_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR3_RT',
 'LO_INC_ENRL_ORIG_YR3_RT',
 'LO_INC_ENRL_4YR_TRANS_YR3_RT',
 'LO_INC_ENRL_2YR_TRANS_YR3_RT',
 'LO_INC_UNKN_ORIG_YR3_RT',
 'LO_INC_UNKN_4YR_TRANS_YR3_RT',
 'LO_INC_UNKN_2YR_TRANS_YR3_RT',
 'MD_INC_DEATH_YR3_RT',
 'MD_INC_COMP_ORIG_YR3_RT',
 'MD_INC_COMP_4YR_TRANS_YR3_RT',
 'MD_INC_COMP_2YR_TRANS_YR3_RT',
 'MD_INC_WDRAW_ORIG_YR3_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR3_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR3_RT',
 'MD_INC_ENRL_ORIG_YR3_RT',
 'MD_INC_ENRL_4YR_TRANS_YR3_RT',
 'MD_INC_ENRL_2YR_TRANS_YR3_RT',
 'MD_INC_UNKN_ORIG_YR3_RT',
 'MD_INC_UNKN_4YR_TRANS_YR3_RT',
 'MD_INC_UNKN_2YR_TRANS_YR3_RT',
 'HI_INC_DEATH_YR3_RT',
 'HI_INC_COMP_ORIG_YR3_RT',
 'HI_INC_COMP_4YR_TRANS_YR3_RT',
 'HI_INC_COMP_2YR_TRANS_YR3_RT',
 'HI_INC_WDRAW_ORIG_YR3_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR3_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR3_RT',
 'HI_INC_ENRL_ORIG_YR3_RT',
 'HI_INC_ENRL_4YR_TRANS_YR3_RT',
 'HI_INC_ENRL_2YR_TRANS_YR3_RT',
 'HI_INC_UNKN_ORIG_YR3_RT',
 'HI_INC_UNKN_4YR_TRANS_YR3_RT',
 'HI_INC_UNKN_2YR_TRANS_YR3_RT',
 'DEP_DEATH_YR3_RT',
 'DEP_COMP_ORIG_YR3_RT',
 'DEP_COMP_4YR_TRANS_YR3_RT',
 'DEP_COMP_2YR_TRANS_YR3_RT',
 'DEP_WDRAW_ORIG_YR3_RT',
 'DEP_WDRAW_4YR_TRANS_YR3_RT',
 'DEP_WDRAW_2YR_TRANS_YR3_RT',
 'DEP_ENRL_ORIG_YR3_RT',
 'DEP_ENRL_4YR_TRANS_YR3_RT',
 'DEP_ENRL_2YR_TRANS_YR3_RT',
 'DEP_UNKN_ORIG_YR3_RT',
 'DEP_UNKN_4YR_TRANS_YR3_RT',
 'DEP_UNKN_2YR_TRANS_YR3_RT',
 'IND_DEATH_YR3_RT',
 'IND_COMP_ORIG_YR3_RT',
 'IND_COMP_4YR_TRANS_YR3_RT',
 'IND_COMP_2YR_TRANS_YR3_RT',
 'IND_WDRAW_ORIG_YR3_RT',
 'IND_WDRAW_4YR_TRANS_YR3_RT',
 'IND_WDRAW_2YR_TRANS_YR3_RT',
 'IND_ENRL_ORIG_YR3_RT',
 'IND_ENRL_4YR_TRANS_YR3_RT',
 'IND_ENRL_2YR_TRANS_YR3_RT',
 'IND_UNKN_ORIG_YR3_RT',
 'IND_UNKN_4YR_TRANS_YR3_RT',
 'IND_UNKN_2YR_TRANS_YR3_RT',
 'FEMALE_DEATH_YR3_RT',
 'FEMALE_COMP_ORIG_YR3_RT',
 'FEMALE_COMP_4YR_TRANS_YR3_RT',
 'FEMALE_COMP_2YR_TRANS_YR3_RT',
 'FEMALE_WDRAW_ORIG_YR3_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR3_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR3_RT',
 'FEMALE_ENRL_ORIG_YR3_RT',
 'FEMALE_ENRL_4YR_TRANS_YR3_RT',
 'FEMALE_ENRL_2YR_TRANS_YR3_RT',
 'FEMALE_UNKN_ORIG_YR3_RT',
 'FEMALE_UNKN_4YR_TRANS_YR3_RT',
 'FEMALE_UNKN_2YR_TRANS_YR3_RT',
 'MALE_DEATH_YR3_RT',
 'MALE_COMP_ORIG_YR3_RT',
 'MALE_COMP_4YR_TRANS_YR3_RT',
 'MALE_COMP_2YR_TRANS_YR3_RT',
 'MALE_WDRAW_ORIG_YR3_RT',
 'MALE_WDRAW_4YR_TRANS_YR3_RT',
 'MALE_WDRAW_2YR_TRANS_YR3_RT',
 'MALE_ENRL_ORIG_YR3_RT',
 'MALE_ENRL_4YR_TRANS_YR3_RT',
 'MALE_ENRL_2YR_TRANS_YR3_RT',
 'MALE_UNKN_ORIG_YR3_RT',
 'MALE_UNKN_4YR_TRANS_YR3_RT',
 'MALE_UNKN_2YR_TRANS_YR3_RT',
 'PELL_DEATH_YR3_RT',
 'PELL_COMP_ORIG_YR3_RT',
 'PELL_COMP_4YR_TRANS_YR3_RT',
 'PELL_COMP_2YR_TRANS_YR3_RT',
 'PELL_WDRAW_ORIG_YR3_RT',
 'PELL_WDRAW_4YR_TRANS_YR3_RT',
 'PELL_WDRAW_2YR_TRANS_YR3_RT',
 'PELL_ENRL_ORIG_YR3_RT',
 'PELL_ENRL_4YR_TRANS_YR3_RT',
 'PELL_ENRL_2YR_TRANS_YR3_RT',
 'PELL_UNKN_ORIG_YR3_RT',
 'PELL_UNKN_4YR_TRANS_YR3_RT',
 'PELL_UNKN_2YR_TRANS_YR3_RT',
 'NOPELL_DEATH_YR3_RT',
 'NOPELL_COMP_ORIG_YR3_RT',
 'NOPELL_COMP_4YR_TRANS_YR3_RT',
 'NOPELL_COMP_2YR_TRANS_YR3_RT',
 'NOPELL_WDRAW_ORIG_YR3_RT',
 'NOPELL_WDRAW_4YR_TRANS_YR3_RT',
 'NOPELL_WDRAW_2YR_TRANS_YR3_RT',
 'NOPELL_ENRL_ORIG_YR3_RT',
 'NOPELL_ENRL_4YR_TRANS_YR3_RT',
 'NOPELL_ENRL_2YR_TRANS_YR3_RT',
 'NOPELL_UNKN_ORIG_YR3_RT',
 'NOPELL_UNKN_4YR_TRANS_YR3_RT',
 'NOPELL_UNKN_2YR_TRANS_YR3_RT',
 'LOAN_DEATH_YR3_RT',
 'LOAN_COMP_ORIG_YR3_RT',
 'LOAN_COMP_4YR_TRANS_YR3_RT',
 'LOAN_COMP_2YR_TRANS_YR3_RT',
 'LOAN_WDRAW_ORIG_YR3_RT',
 'LOAN_WDRAW_4YR_TRANS_YR3_RT',
 'LOAN_WDRAW_2YR_TRANS_YR3_RT',
 'LOAN_ENRL_ORIG_YR3_RT',
 'LOAN_ENRL_4YR_TRANS_YR3_RT',
 'LOAN_ENRL_2YR_TRANS_YR3_RT',
 'LOAN_UNKN_ORIG_YR3_RT',
 'LOAN_UNKN_4YR_TRANS_YR3_RT',
 'LOAN_UNKN_2YR_TRANS_YR3_RT',
 'NOLOAN_DEATH_YR3_RT',
 'NOLOAN_COMP_ORIG_YR3_RT',
 'NOLOAN_COMP_4YR_TRANS_YR3_RT',
 'NOLOAN_COMP_2YR_TRANS_YR3_RT',
 'NOLOAN_WDRAW_ORIG_YR3_RT',
 'NOLOAN_WDRAW_4YR_TRANS_YR3_RT',
 'NOLOAN_WDRAW_2YR_TRANS_YR3_RT',
 'NOLOAN_ENRL_ORIG_YR3_RT',
 'NOLOAN_ENRL_4YR_TRANS_YR3_RT',
 'NOLOAN_ENRL_2YR_TRANS_YR3_RT',
 'NOLOAN_UNKN_ORIG_YR3_RT',
 'NOLOAN_UNKN_4YR_TRANS_YR3_RT',
 'NOLOAN_UNKN_2YR_TRANS_YR3_RT',
 'FIRSTGEN_DEATH_YR3_RT',
 'FIRSTGEN_COMP_ORIG_YR3_RT',
 'FIRSTGEN_COMP_4YR_TRANS_YR3_RT',
 'FIRSTGEN_COMP_2YR_TRANS_YR3_RT',
 'FIRSTGEN_WDRAW_ORIG_YR3_RT',
 'FIRSTGEN_WDRAW_4YR_TRANS_YR3_RT',
 'FIRSTGEN_WDRAW_2YR_TRANS_YR3_RT',
 'FIRSTGEN_ENRL_ORIG_YR3_RT',
 'FIRSTGEN_ENRL_4YR_TRANS_YR3_RT',
 'FIRSTGEN_ENRL_2YR_TRANS_YR3_RT',
 'FIRSTGEN_UNKN_ORIG_YR3_RT',
 'FIRSTGEN_UNKN_4YR_TRANS_YR3_RT',
 'FIRSTGEN_UNKN_2YR_TRANS_YR3_RT',
 'NOT1STGEN_DEATH_YR3_RT',
 'NOT1STGEN_COMP_ORIG_YR3_RT',
 'NOT1STGEN_COMP_4YR_TRANS_YR3_RT',
 'NOT1STGEN_COMP_2YR_TRANS_YR3_RT',
 'NOT1STGEN_WDRAW_ORIG_YR3_RT',
 'NOT1STGEN_WDRAW_4YR_TRANS_YR3_RT',
 'NOT1STGEN_WDRAW_2YR_TRANS_YR3_RT',
 'NOT1STGEN_ENRL_ORIG_YR3_RT',
 'NOT1STGEN_ENRL_4YR_TRANS_YR3_RT',
 'NOT1STGEN_ENRL_2YR_TRANS_YR3_RT',
 'NOT1STGEN_UNKN_ORIG_YR3_RT',
 'NOT1STGEN_UNKN_4YR_TRANS_YR3_RT',
 'NOT1STGEN_UNKN_2YR_TRANS_YR3_RT',
 'DEATH_YR4_RT',
 'COMP_ORIG_YR4_RT',
 'COMP_4YR_TRANS_YR4_RT',
 'COMP_2YR_TRANS_YR4_RT',
 'WDRAW_ORIG_YR4_RT',
 'WDRAW_4YR_TRANS_YR4_RT',
 'WDRAW_2YR_TRANS_YR4_RT',
 'ENRL_ORIG_YR4_RT',
 'ENRL_4YR_TRANS_YR4_RT',
 'ENRL_2YR_TRANS_YR4_RT',
 'UNKN_ORIG_YR4_RT',
 'UNKN_4YR_TRANS_YR4_RT',
 'UNKN_2YR_TRANS_YR4_RT',
 'LO_INC_DEATH_YR4_RT',
 'LO_INC_COMP_ORIG_YR4_RT',
 'LO_INC_COMP_4YR_TRANS_YR4_RT',
 'LO_INC_COMP_2YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_ORIG_YR4_RT',
 'LO_INC_WDRAW_4YR_TRANS_YR4_RT',
 'LO_INC_WDRAW_2YR_TRANS_YR4_RT',
 'LO_INC_ENRL_ORIG_YR4_RT',
 'LO_INC_ENRL_4YR_TRANS_YR4_RT',
 'LO_INC_ENRL_2YR_TRANS_YR4_RT',
 'LO_INC_UNKN_ORIG_YR4_RT',
 'LO_INC_UNKN_4YR_TRANS_YR4_RT',
 'LO_INC_UNKN_2YR_TRANS_YR4_RT',
 'MD_INC_DEATH_YR4_RT',
 'MD_INC_COMP_ORIG_YR4_RT',
 'MD_INC_COMP_4YR_TRANS_YR4_RT',
 'MD_INC_COMP_2YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_ORIG_YR4_RT',
 'MD_INC_WDRAW_4YR_TRANS_YR4_RT',
 'MD_INC_WDRAW_2YR_TRANS_YR4_RT',
 'MD_INC_ENRL_ORIG_YR4_RT',
 'MD_INC_ENRL_4YR_TRANS_YR4_RT',
 'MD_INC_ENRL_2YR_TRANS_YR4_RT',
 'MD_INC_UNKN_ORIG_YR4_RT',
 'MD_INC_UNKN_4YR_TRANS_YR4_RT',
 'MD_INC_UNKN_2YR_TRANS_YR4_RT',
 'HI_INC_DEATH_YR4_RT',
 'HI_INC_COMP_ORIG_YR4_RT',
 'HI_INC_COMP_4YR_TRANS_YR4_RT',
 'HI_INC_COMP_2YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_ORIG_YR4_RT',
 'HI_INC_WDRAW_4YR_TRANS_YR4_RT',
 'HI_INC_WDRAW_2YR_TRANS_YR4_RT',
 'HI_INC_ENRL_ORIG_YR4_RT',
 'HI_INC_ENRL_4YR_TRANS_YR4_RT',
 'HI_INC_ENRL_2YR_TRANS_YR4_RT',
 'HI_INC_UNKN_ORIG_YR4_RT',
 'HI_INC_UNKN_4YR_TRANS_YR4_RT',
 'HI_INC_UNKN_2YR_TRANS_YR4_RT',
 'DEP_DEATH_YR4_RT',
 'DEP_COMP_ORIG_YR4_RT',
 'DEP_COMP_4YR_TRANS_YR4_RT',
 'DEP_COMP_2YR_TRANS_YR4_RT',
 'DEP_WDRAW_ORIG_YR4_RT',
 'DEP_WDRAW_4YR_TRANS_YR4_RT',
 'DEP_WDRAW_2YR_TRANS_YR4_RT',
 'DEP_ENRL_ORIG_YR4_RT',
 'DEP_ENRL_4YR_TRANS_YR4_RT',
 'DEP_ENRL_2YR_TRANS_YR4_RT',
 'DEP_UNKN_ORIG_YR4_RT',
 'DEP_UNKN_4YR_TRANS_YR4_RT',
 'DEP_UNKN_2YR_TRANS_YR4_RT',
 'IND_DEATH_YR4_RT',
 'IND_COMP_ORIG_YR4_RT',
 'IND_COMP_4YR_TRANS_YR4_RT',
 'IND_COMP_2YR_TRANS_YR4_RT',
 'IND_WDRAW_ORIG_YR4_RT',
 'IND_WDRAW_4YR_TRANS_YR4_RT',
 'IND_WDRAW_2YR_TRANS_YR4_RT',
 'IND_ENRL_ORIG_YR4_RT',
 'IND_ENRL_4YR_TRANS_YR4_RT',
 'IND_ENRL_2YR_TRANS_YR4_RT',
 'IND_UNKN_ORIG_YR4_RT',
 'IND_UNKN_4YR_TRANS_YR4_RT',
 'IND_UNKN_2YR_TRANS_YR4_RT',
 'FEMALE_DEATH_YR4_RT',
 'FEMALE_COMP_ORIG_YR4_RT',
 'FEMALE_COMP_4YR_TRANS_YR4_RT',
 'FEMALE_COMP_2YR_TRANS_YR4_RT',
 'FEMALE_WDRAW_ORIG_YR4_RT',
 'FEMALE_WDRAW_4YR_TRANS_YR4_RT',
 'FEMALE_WDRAW_2YR_TRANS_YR4_RT',
 'FEMALE_ENRL_ORIG_YR4_RT',
 'FEMALE_ENRL_4YR_TRANS_YR4_RT',
 'FEMALE_ENRL_2YR_TRANS_YR4_RT',
 'FEMALE_UNKN_ORIG_YR4_RT',
 'FEMALE_UNKN_4YR_TRANS_YR4_RT',
 'FEMALE_UNKN_2YR_TRANS_YR4_RT',
 'MALE_DEATH_YR4_RT',
 'MALE_COMP_ORIG_YR4_RT',
 'MALE_COMP_4YR_TRANS_YR4_RT',
 'MALE_COMP_2YR_TRANS_YR4_RT',
 'MALE_WDRAW_ORIG_YR4_RT',
 'MALE_WDRAW_4YR_TRANS_YR4_RT',
 'MALE_WDRAW_2YR_TRANS_YR4_RT',

In [52]:
# Drop the columns

"""
Manually selected columns:
8-digit OPE ID for institution, 6-digit OPE ID for institution, State postcode, 
ZIP code, URL for institution's homepage, URL for institution's net price calculator

Full of null columns:
see the code below
"""

# Drop manually selected columns

drop_columns=['OPEID','OPEID6','STABBR','ZIP','INSTURL','NPCURL','LATITUDE','LONGITUDE'] 
data = data.drop(columns=drop_columns)

(2326, 1969)

In [55]:

# Drop columns full of null
data= data.dropna(axis = 'columns', how='all')
data.shape

(2326, 1657)

In [ ]:
# Drop row full of null

In [40]:
# test size: 0.33