In [1]:
import pandas as pd
import numpy as np
import sklearn.metrics
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.neural_network import MLPRegressor

from sklearn.model_selection import cross_validate
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

from sklearn.preprocessing import PolynomialFeatures 

from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from scipy.sparse import csr_matrix, hstack

import tensorflow as tf
import keras
import time
from keras.models import Sequential

from sklearn.model_selection import GridSearchCV

Using TensorFlow backend.

In [2]:
df_96 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED1996_97_PP.csv")
df_97 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED1997_98_PP.csv")
df_98 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED1998_99_PP.csv")
df_99 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED1999_00_PP.csv")
df_00 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2000_01_PP.csv")
df_01 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2001_02_PP.csv")
df_02 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2002_03_PP.csv")
df_03 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2003_04_PP.csv")
df_04 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2004_05_PP.csv")
df_05 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2005_06_PP.csv")
df_06 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2006_07_PP.csv")
df_07 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2007_08_PP.csv")
df_08 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2008_09_PP.csv")
df_09 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2009_10_PP.csv")
df_10 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2010_11_PP.csv")
df_11 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2011_12_PP.csv")
df_12 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2012_13_PP.csv")
df_13 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2013_14_PP.csv")
df_14 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2014_15_PP.csv")
df_15 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2015_16_PP.csv")
df_16 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2016_17_PP.csv")
df_17 = pd.read_csv("CollegeScorecard_Raw_Data/MERGED2017_18_PP.csv")

/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1806,1814) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1,6,442,451,598,607,611,620,624,633,789,802,806,815,971,984,997,1153,1166,1407,1408,1411,1424,1425,1426,1431,1432,1433,1437,1438,1439,1440,1445,1446,1447,1451,1452,1453,1454,1459,1460,1461,1465,1466,1467,1468,1473,1474,1475,1479,1480,1481,1482,1487,1488,1489,1501,1502,1537,1538,1539,1540,1541,1542,1606,1609,1610,1611,1613,1614,1615,1616,1688,1689,1690,1691,1692,1908,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1,1408,1431,1432,1433,1489,1537,1538,1539,1540,1542,1606,1610,1611,1614,1615,1616,1729) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1,1447,1537,1540,1542,1606,1614,1615) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1,1537,1540,1542,1606,1614,1615) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1,6,1461,1561,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1537,1540,1542,1575,1606,1614,1615,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1537,1540,1542,1547,1548,1549,1561,1575,1606,1614,1615,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (6,1169,1170,1171,1172,1173,1174,1175,1177,1178,1179,1180,1183,1184,1185,1186,1187,1188,1196,1199,1200,1209,1212,1213,1222,1223,1224,1225,1226,1227,1235,1236,1237,1238,1239,1240,1248,1251,1252,1253,1255,1257,1261,1264,1265,1266,1268,1270,1274,1275,1276,1277,1278,1279,1281,1287,1288,1289,1290,1291,1292,1294,1303,1304,1316,1317,1326,1327,1328,1329,1330,1331,1335,1339,1340,1341,1342,1343,1344,1348,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1411,1426,1427,1475,1476,1479,1480,1483,1484,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1517,1529,1530,1532,1537,1540,1541,1542,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1606,1609,1610,1613,1614,1615,1708,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (6,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (6,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1431,1432,1503,1504,1517,1518,1519,1529,1530,1531,1532,1534,1535,1537,1538,1539,1540,1542,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1606,1610,1611,1614,1615,1616,1708,1729,1909,1910,1911,1912,1913) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (31,1726,1727,1728,1729,1815,1817,1823,1830,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
frames = [
    df_96, df_97, df_98, 
    df_99, df_00, df_01, 
    df_02, df_03, df_04, 
    df_05, df_06, df_07, 
    df_08, df_09, df_10,
    df_11, df_12, df_13, 
    df_14, df_15, df_16, 
    df_17
]
data = pd.concat(frames)

In [4]:
data['GRAD_DEBT_MDN'].describe()

count                137486
unique                21488
top       PrivacySuppressed
freq                  35382
Name: GRAD_DEBT_MDN, dtype: object

In [5]:
print(data.shape)
data = data.set_index('UNITID')
data.head()

(154282, 1977)

,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,SCH_DEG,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
UNITID,,,,,,,,,,,,,,,,,,,,,
100636,01230800,12308,Community College of the Air Force,Montgomery,AL,36114-3011,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100654,00100200,1002,Alabama A & M University,Normal,AL,35762,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100663,00105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100672,00574900,5749,ALABAMA AVIATION AND TECHNICAL COLLEGE,OZARK,AL,36360,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100690,02503400,25034,Amridge University,Montgomery,AL,36117-3553,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data = data.replace('PrivacySuppressed', np.nan)
data = data.replace('null', np.nan)
print(data.shape)

(154282, 1976)

In [7]:
cols_to_remove = [
    #irrelevant data
    'OPEID',
    'OPEID6',
    'INSTNM',
    'ZIP',
    'INSTURL',
    'NPCURL',
    'LATITUDE',
    'LONGITUDE',
    'ALIAS',
    'CIPTITLE1',
    'CIPTITLE2',
    'CIPTITLE3',
    'CIPTITLE4',
    'CIPTITLE5',
    'CIPTITLE6',
    
    #date fields:
    'REPAY_DT_MDN',
    'SEPAR_DT_MDN',
    'T4APPROVALDATE',
    
    #earnings data
    'MD_EARN_WNE_P10',
    'COUNT_ED',
    'COUNT_NWNE_P10',
    'COUNT_WNE_P10',
    'MN_EARN_WNE_P10',
    'PCT10_EARN_WNE_P10',
    'PCT25_EARN_WNE_P10',
    'PCT75_EARN_WNE_P10',
    'PCT90_EARN_WNE_P10',
    'SD_EARN_WNE_P10',
    'COUNT_WNE_INC1_P10',
    'COUNT_WNE_INC2_P10',
    'COUNT_WNE_INC3_P10',
    'COUNT_WNE_INDEP0_INC1_P10',
    'COUNT_WNE_INDEP0_P10',
    'COUNT_WNE_INDEP1_P10',
    'COUNT_WNE_MALE0_P10',
    'COUNT_WNE_MALE1_P10',
    'GT_25K_P10',
    'GT_28K_P10',
    'MN_EARN_WNE_INC1_P10',
    'MN_EARN_WNE_INC2_P10',
    'MN_EARN_WNE_INC3_P10',
    'MN_EARN_WNE_INDEP0_INC1_P10',
    'MN_EARN_WNE_INDEP0_P10',
    'MN_EARN_WNE_INDEP1_P10',
    'MN_EARN_WNE_MALE0_P10',
    'MN_EARN_WNE_MALE1_P10',
    'COUNT_NWNE_P6',
    'COUNT_WNE_P6',
    'MN_EARN_WNE_P6',
    'MD_EARN_WNE_P6',
    'PCT10_EARN_WNE_P6',
    'PCT25_EARN_WNE_P6',
    'PCT75_EARN_WNE_P6',
    'PCT90_EARN_WNE_P6',
    'SD_EARN_WNE_P6',
    'COUNT_WNE_INC1_P6',
    'COUNT_WNE_INC2_P6',
    'COUNT_WNE_INC3_P6',
    'COUNT_WNE_INDEP0_INC1_P6',
    'COUNT_WNE_INDEP0_P6',
    'COUNT_WNE_INDEP1_P6',
    'COUNT_WNE_MALE0_P6',
    'COUNT_WNE_MALE1_P6',
    'GT_25K_P6',
    'GT_28K_P6',
    'MN_EARN_WNE_INC1_P6',
    'MN_EARN_WNE_INC2_P6',
    'MN_EARN_WNE_INC3_P6',
    'MN_EARN_WNE_INDEP0_INC1_P6',
    'MN_EARN_WNE_INDEP0_P6',
    'MN_EARN_WNE_INDEP1_P6',
    'MN_EARN_WNE_MALE0_P6',
    'MN_EARN_WNE_MALE1_P6',
    'COUNT_NWNE_P7',
    'COUNT_WNE_P7',
    'MN_EARN_WNE_P7',
    'SD_EARN_WNE_P7',
    'GT_25K_P7',
    'COUNT_NWNE_P8',
    'COUNT_WNE_P8',
    'MN_EARN_WNE_P8',
    'MD_EARN_WNE_P8',
    'PCT10_EARN_WNE_P8',
    'PCT25_EARN_WNE_P8',
    'PCT75_EARN_WNE_P8',
    'PCT90_EARN_WNE_P8',
    'SD_EARN_WNE_P8',
    'GT_25K_P8',
    'GT_28K_P8',
    'COUNT_NWNE_P9',
    'COUNT_WNE_P9',
    'MN_EARN_WNE_P9',
    'SD_EARN_WNE_P9',
    'GT_25K_P9',
    
    #aid:
    'PCTPELL',
    'PCTFLOAN',
    'DEBT_MDN',
    'WDRAW_DEBT_MDN',
    'LO_INC_DEBT_MDN',
    'MD_INC_DEBT_MDN',
    'HI_INC_DEBT_MDN',
    'DEP_DEBT_MDN',
    'IND_DEBT_MDN',
    'PELL_DEBT_MDN',
    'NOPELL_DEBT_MDN',
    'FEMALE_DEBT_MDN',
    'MALE_DEBT_MDN',
    'FIRSTGEN_DEBT_MDN',
    'NOTFIRSTGEN_DEBT_MDN',
    'DEBT_N',
    'GRAD_DEBT_N',
    'WDRAW_DEBT_N',
    'LO_INC_DEBT_N',
    'MD_INC_DEBT_N',
    'HI_INC_DEBT_N',
    'DEP_DEBT_N',
    'IND_DEBT_N',
    'PELL_DEBT_N',
    'NOPELL_DEBT_N',
    'FEMALE_DEBT_N',
    'MALE_DEBT_N',
    'FIRSTGEN_DEBT_N',
    'NOTFIRSTGEN_DEBT_N',
    'GRAD_DEBT_MDN10YR',
    'CUML_DEBT_N',
    'CUML_DEBT_P90',
    'CUML_DEBT_P75',
    'CUML_DEBT_P25',
    'CUML_DEBT_P10',
    'LOAN_EVER',
    'DEBT_MDN_SUPP',
    'GRAD_DEBT_MDN_SUPP',
    'GRAD_DEBT_MDN10YR_SUPP',
    
    #repayment
    'CDR2',
    'CDR3',
    'RPY_1YR_RT',
    'COMPL_RPY_1YR_RT',
    'NONCOM_RPY_1YR_RT',
    'LO_INC_RPY_1YR_RT',
    'MD_INC_RPY_1YR_RT',
    'HI_INC_RPY_1YR_RT',
    'DEP_RPY_1YR_RT',
    'IND_RPY_1YR_RT',
    'PELL_RPY_1YR_RT',
    'NOPELL_RPY_1YR_RT',
    'FEMALE_RPY_1YR_RT',
    'MALE_RPY_1YR_RT',
    'FIRSTGEN_RPY_1YR_RT',
    'NOTFIRSTGEN_RPY_1YR_RT',
    'RPY_3YR_RT',
    'COMPL_RPY_3YR_RT',
    'NONCOM_RPY_3YR_RT',
    'LO_INC_RPY_3YR_RT',
    'MD_INC_RPY_3YR_RT',
    'HI_INC_RPY_3YR_RT',
    'DEP_RPY_3YR_RT',
    'IND_RPY_3YR_RT',
    'PELL_RPY_3YR_RT',
    'NOPELL_RPY_3YR_RT',
    'FEMALE_RPY_3YR_RT',
    'MALE_RPY_3YR_RT',
    'FIRSTGEN_RPY_3YR_RT',
    'NOTFIRSTGEN_RPY_3YR_RT',
    'RPY_5YR_RT',
    'COMPL_RPY_5YR_RT',
    'NONCOM_RPY_5YR_RT',
    'LO_INC_RPY_5YR_RT',
    'MD_INC_RPY_5YR_RT',
    'HI_INC_RPY_5YR_RT',
    'DEP_RPY_5YR_RT',
    'IND_RPY_5YR_RT',
    'PELL_RPY_5YR_RT',
    'NOPELL_RPY_5YR_RT',
    'FEMALE_RPY_5YR_RT',
    'MALE_RPY_5YR_RT',
    'FIRSTGEN_RPY_5YR_RT',
    'NOTFIRSTGEN_RPY_5YR_RT',
    'RPY_7YR_RT',
    'COMPL_RPY_7YR_RT',
    'NONCOM_RPY_7YR_RT',
    'LO_INC_RPY_7YR_RT',
    'MD_INC_RPY_7YR_RT',
    'HI_INC_RPY_7YR_RT',
    'DEP_RPY_7YR_RT',
    'IND_RPY_7YR_RT',
    'PELL_RPY_7YR_RT',
    'NOPELL_RPY_7YR_RT',
    'FEMALE_RPY_7YR_RT',
    'MALE_RPY_7YR_RT',
    'FIRSTGEN_RPY_7YR_RT',
    'NOTFIRSTGEN_RPY_7YR_RT',
    'REPAY_DT_MDN',
    'REPAY_DT_N',
    'RPY_1YR_N',
    'COMPL_RPY_1YR_N',
    'NONCOM_RPY_1YR_N',
    'LO_INC_RPY_1YR_N',
    'MD_INC_RPY_1YR_N',
    'HI_INC_RPY_1YR_N',
    'DEP_RPY_1YR_N',
    'IND_RPY_1YR_N',
    'PELL_RPY_1YR_N',
    'NOPELL_RPY_1YR_N',
    'FEMALE_RPY_1YR_N',
    'MALE_RPY_1YR_N',
    'FIRSTGEN_RPY_1YR_N',
    'NOTFIRSTGEN_RPY_1YR_N',
    'RPY_3YR_N',
    'COMPL_RPY_3YR_N',
    'NONCOM_RPY_3YR_N',
    'LO_INC_RPY_3YR_N',
    'MD_INC_RPY_3YR_N',
    'HI_INC_RPY_3YR_N',
    'DEP_RPY_3YR_N',
    'IND_RPY_3YR_N',
    'PELL_RPY_3YR_N',
    'NOPELL_RPY_3YR_N',
    'FEMALE_RPY_3YR_N',
    'MALE_RPY_3YR_N',
    'FIRSTGEN_RPY_3YR_N',
    'NOTFIRSTGEN_RPY_3YR_N',
    'RPY_5YR_N',
    'COMPL_RPY_5YR_N',
    'NONCOM_RPY_5YR_N',
    'LO_INC_RPY_5YR_N',
    'MD_INC_RPY_5YR_N',
    'HI_INC_RPY_5YR_N',
    'DEP_RPY_5YR_N',
    'IND_RPY_5YR_N',
    'PELL_RPY_5YR_N',
    'NOPELL_RPY_5YR_N',
    'FEMALE_RPY_5YR_N',
    'MALE_RPY_5YR_N',
    'FIRSTGEN_RPY_5YR_N',
    'NOTFIRSTGEN_RPY_5YR_N',
    'RPY_7YR_N',
    'COMPL_RPY_7YR_N',
    'NONCOM_RPY_7YR_N',
    'LO_INC_RPY_7YR_N',
    'MD_INC_RPY_7YR_N',
    'HI_INC_RPY_7YR_N',
    'DEP_RPY_7YR_N',
    'IND_RPY_7YR_N',
    'PELL_RPY_7YR_N',
    'NOPELL_RPY_7YR_N',
    'FEMALE_RPY_7YR_N',
    'MALE_RPY_7YR_N',
    'FIRSTGEN_RPY_7YR_N',
    'NOTFIRSTGEN_RPY_7YR_N',
    'RPY_3YR_RT_SUPP',
    'LO_INC_RPY_3YR_RT_SUPP',
    'MD_INC_RPY_3YR_RT_SUPP',
    'HI_INC_RPY_3YR_RT_SUPP',
    'COMPL_RPY_3YR_RT_SUPP',
    'NONCOM_RPY_3YR_RT_SUPP',
    'DEP_RPY_3YR_RT_SUPP',
    'IND_RPY_3YR_RT_SUPP',
    'PELL_RPY_3YR_RT_SUPP',
    'NOPELL_RPY_3YR_RT_SUPP',
    'FEMALE_RPY_3YR_RT_SUPP',
    'MALE_RPY_3YR_RT_SUPP',
    'FIRSTGEN_RPY_3YR_RT_SUPP',
    'NOTFIRSTGEN_RPY_3YR_RT_SUPP',
    'CDR2_DENOM',
    'CDR3_DENOM'
]
data = data.drop(columns=cols_to_remove)

In [8]:
##Drop rows with nulls for our Y column
data = data.dropna(subset=['GRAD_DEBT_MDN'])
print(data.shape)

(102104, 1712)

In [9]:
print(data.shape)

data = data.dropna(axis='columns', how='all')
print(data.shape)

data = data.dropna(axis='rows', how='all')
print(data.shape)

data.head()

(102104, 1712)
(102104, 1564)
(102104, 1564)

,CITY,STABBR,SCH_DEG,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,ST_FIPS,REGION,...,OMAWDP8_NOTFIRSTTIME,OMENRUP_NOTFIRSTTIME,OMENRYP_FULLTIME,OMENRAP_FULLTIME,OMAWDP8_FULLTIME,OMENRUP_FULLTIME,OMENRYP_PARTTIME,OMENRAP_PARTTIME,OMAWDP8_PARTTIME,OMENRUP_PARTTIME
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,Normal,AL,NaN,1,1,3,4,1.0,1.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100663,Birmingham,AL,NaN,1,2,3,4,1.0,1.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100706,Huntsville,AL,NaN,1,1,3,4,1.0,1.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100751,Tuscaloosa,AL,NaN,1,1,3,4,1.0,1.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100812,Athens,AL,NaN,1,1,3,3,1.0,1.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data['GRAD_DEBT_MDN'].describe()

count     102104
unique     21487
top         9500
freq        4124
Name: GRAD_DEBT_MDN, dtype: object

In [11]:
cats = [
#index:'UNITID',
'CITY',
'STABBR',
'ACCREDAGENCY',
'SCH_DEG',
'HCM2',
'MAIN',
'PREDDEG',
'HIGHDEG',
'CONTROL',
'ST_FIPS',
'REGION',
'LOCALE',
'LOCALE2',
'CCBASIC',
'CCUGPROF',
'CCSIZSET',
'HBCU',
'PBI',
'ANNHI',
'TRIBAL',
'AANAPII',
'HSI',
'NANTI',
'MENONLY',
'WOMENONLY',
'RELAFFIL',
'DISTANCEONLY',
'CURROPER',
'ICLEVEL',
'OPENADMP',
'ACCREDCODE',
'POOLYRSRET_FT',
'POOLYRSRET_PT',    
'POOLYRS100',
'POOLYRSOM_FTFT',
'POOLYRSOM_PTFT',
'POOLYRSOM_FTNFT',
'POOLYRSOM_PTNFT',
'SCHTYPE',
'OPEFLAG',
'CIPCODE1',
'CIPCODE2',
'CIPCODE3',
'CIPCODE4',
'CIPCODE5',
'CIPCODE6',
'POOLYRSOM_ALL',
'POOLYRSOM_FIRSTTIME',
'POOLYRSOM_NOTFIRSTTIME',
'POOLYRSOM_FULLTIME',
'POOLYRSOM_PARTTIME'
]

In [12]:
#convert columns into floats where possible, one-hot-encode others
#cats = []
for i in data.columns:
    if data[i].dtype == "object":
        try:
            data[i] = data[i].astype('float64')
            if data[i].mean() == np.nan:
                print("mean=null")
                print(i)
                data = data.drop(columns=i)
            else:
                data[i] = data[i].fillna(data[i].mean())
        except:
            #cats.append(i)
            if i not in cats:
                print("not in cats")
                print("dropping: " + str(i))
                data = data.drop(columns=i)
            else:
                data[i] = data[i].fillna("null")
    elif data[i].dtype == "float64":
        data[i] = data[i].fillna(data[i].mean())

not in cats
dropping: RET_FTL4_POOLED

In [13]:
#drop category columns from array if column was already eliminated from dataset
remaining = []
for i in cats:
    print(i)
    try:
        data[i].head(1)
        print("Keeping: " + str(i))
        #print()
        remaining.append(i)
    except:
        print("removing: " + str(i))
cats=remaining
cats

CITY
Keeping: CITY
STABBR
Keeping: STABBR
ACCREDAGENCY
removing: ACCREDAGENCY
SCH_DEG
Keeping: SCH_DEG
HCM2
removing: HCM2
MAIN
Keeping: MAIN
PREDDEG
Keeping: PREDDEG
HIGHDEG
Keeping: HIGHDEG
CONTROL
Keeping: CONTROL
ST_FIPS
Keeping: ST_FIPS
REGION
Keeping: REGION
LOCALE
removing: LOCALE
LOCALE2
removing: LOCALE2
CCBASIC
removing: CCBASIC
CCUGPROF
removing: CCUGPROF
CCSIZSET
removing: CCSIZSET
HBCU
removing: HBCU
PBI
removing: PBI
ANNHI
removing: ANNHI
TRIBAL
removing: TRIBAL
AANAPII
removing: AANAPII
HSI
removing: HSI
NANTI
removing: NANTI
MENONLY
removing: MENONLY
WOMENONLY
removing: WOMENONLY
RELAFFIL
removing: RELAFFIL
DISTANCEONLY
Keeping: DISTANCEONLY
CURROPER
removing: CURROPER
ICLEVEL
Keeping: ICLEVEL
OPENADMP
Keeping: OPENADMP
ACCREDCODE
removing: ACCREDCODE
POOLYRSRET_FT
removing: POOLYRSRET_FT
POOLYRSRET_PT
Keeping: POOLYRSRET_PT
POOLYRS100
removing: POOLYRS100
POOLYRSOM_FTFT
removing: POOLYRSOM_FTFT
POOLYRSOM_PTFT
removing: POOLYRSOM_PTFT
POOLYRSOM_FTNFT
removing: POOLYRSOM_FTNFT
POOLYRSOM_PTNFT
removing: POOLYRSOM_PTNFT
SCHTYPE
removing: SCHTYPE
OPEFLAG
removing: OPEFLAG
CIPCODE1
Keeping: CIPCODE1
CIPCODE2
Keeping: CIPCODE2
CIPCODE3
Keeping: CIPCODE3
CIPCODE4
Keeping: CIPCODE4
CIPCODE5
Keeping: CIPCODE5
CIPCODE6
Keeping: CIPCODE6
POOLYRSOM_ALL
removing: POOLYRSOM_ALL
POOLYRSOM_FIRSTTIME
removing: POOLYRSOM_FIRSTTIME
POOLYRSOM_NOTFIRSTTIME
removing: POOLYRSOM_NOTFIRSTTIME
POOLYRSOM_FULLTIME
removing: POOLYRSOM_FULLTIME
POOLYRSOM_PARTTIME
removing: POOLYRSOM_PARTTIME

['CITY',
 'STABBR',
 'SCH_DEG',
 'MAIN',
 'PREDDEG',
 'HIGHDEG',
 'CONTROL',
 'ST_FIPS',
 'REGION',
 'DISTANCEONLY',
 'ICLEVEL',
 'OPENADMP',
 'POOLYRSRET_PT',
 'CIPCODE1',
 'CIPCODE2',
 'CIPCODE3',
 'CIPCODE4',
 'CIPCODE5',
 'CIPCODE6']

In [14]:
y = data['GRAD_DEBT_MDN']
y = y.astype("float64")
X = data.drop(columns=['GRAD_DEBT_MDN'])

In [15]:
y.describe()

count    102104.000000
mean      12522.620867
std        7224.320965
min         500.000000
25%        6625.000000
50%       10991.000000
75%       17125.000000
max       53831.500000
Name: GRAD_DEBT_MDN, dtype: float64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
X_train.head()

,CITY,STABBR,SCH_DEG,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,ST_FIPS,REGION,...,OMAWDP8_NOTFIRSTTIME,OMENRUP_NOTFIRSTTIME,OMENRYP_FULLTIME,OMENRAP_FULLTIME,OMAWDP8_FULLTIME,OMENRUP_FULLTIME,OMENRYP_PARTTIME,OMENRAP_PARTTIME,OMAWDP8_PARTTIME,OMENRUP_PARTTIME
UNITID,,,,,,,,,,,,,,,,,,,,,
157766,Louisville,KY,1.0,1,2,1,2,3.0,21.0,5.0,...,0.539515,0.296574,0.008923,0.164048,0.530007,0.297021,0.017771,0.181587,0.356265,0.444376
155520,Olathe,KS,3.0,1,1,3,4,2.0,20.0,4.0,...,0.539515,0.296574,0.008923,0.164048,0.530007,0.297021,0.017771,0.181587,0.356265,0.444376
155317,Lawrence,KS,3.0,1,1,3,4,1.0,20.0,4.0,...,0.539515,0.296574,0.008923,0.164048,0.530007,0.297021,0.017771,0.181587,0.356265,0.444376
431877,Liberty,NY,1.0,1,1,1,1,1.0,36.0,2.0,...,0.539515,0.296574,0.008923,0.164048,0.530007,0.297021,0.017771,0.181587,0.356265,0.444376
230746,Salt Lake City,UT,2.0,1,2,2,2,1.0,49.0,7.0,...,0.539515,0.296574,0.008923,0.164048,0.530007,0.297021,0.017771,0.181587,0.356265,0.444376

In [17]:
y_train.describe()

count    68409.000000
mean     12528.848309
std       7220.795921
min        500.000000
25%       6625.000000
50%      11000.000000
75%      17125.000000
max      51488.500000
Name: GRAD_DEBT_MDN, dtype: float64

In [18]:
### One Hot Encoding
enc = preprocessing.OneHotEncoder(handle_unknown='ignore')
enc.fit(X_train[cats])
ohe_train = enc.transform(X_train[cats])
ohe_test = enc.transform(X_test[cats])

In [19]:
### Scaling
scaler = StandardScaler()
scaler.fit(X_train.drop(columns=cats))
scaled_train = csr_matrix(scaler.transform(X_train.drop(columns=cats)))
scaled_test = csr_matrix(scaler.transform(X_test.drop(columns=cats)))

In [20]:
X_mat_train = hstack((ohe_train, scaled_train))
X_mat_test = hstack((ohe_test, scaled_test))
X_mat_train

<68409x6857 sparse matrix of type '<class 'numpy.float64'>'
	with 106854858 stored elements in COOrdinate format>

In [22]:
#### Neural Network
mlp = MLPRegressor()
mlp.fit(X_mat_train, y_train)

mlp_train_pred = mlp.predict(X_mat_train)
mlp_pred = mlp.predict(X_mat_test)

print("Train MSE: " + str(mean_squared_error(y_train, mlp_train_pred)))
print("Train RMSE: " + str(np.sqrt(mean_squared_error(y_train, mlp_train_pred))))
print("Train MAE: " + str(mean_absolute_error(y_train, mlp_train_pred)))
print("Train r2: " + str(r2_score(y_train, mlp_train_pred)))
print()
print("Test MSE: " + str(mean_squared_error(y_test, mlp_pred)))
print("Test RMSE: " + str(np.sqrt(mean_squared_error(y_test, mlp_pred))))
print("Test MAE: " + str(mean_absolute_error(y_test, mlp_pred)))
print("Test r2: " + str(r2_score(y_test, mlp_pred)))

/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

Train MSE: 2508036.612428258
Train RMSE: 1583.678190930297
Train MAE: 1066.834155479536
Train r2: 0.9518972307850824

Test MSE: 5524803.078525658
Test RMSE: 2350.4899656296466
Test MAE: 1488.928374473371
Test r2: 0.894351013618801

In [24]:
### Ensemble Boosting
boost = GradientBoostingRegressor()
boost.fit(X_mat_train, y_train)

boost_train_pred = boost.predict(X_mat_train)
boost_pred = boost.predict(X_mat_test)

print("Train MSE: " + str(mean_squared_error(y_train, boost_train_pred)))
print("Train RMSE: " + str(np.sqrt(mean_squared_error(y_train, boost_train_pred))))
print("Train MAE: " + str(mean_absolute_error(y_train, boost_train_pred)))
print("Train r2: " + str(r2_score(y_train, boost_train_pred)))
print()
print("Test MSE: " + str(mean_squared_error(y_test, boost_pred)))
print("Test RMSE: " + str(np.sqrt(mean_squared_error(y_test, boost_pred))))
print("Test MAE: " + str(mean_absolute_error(y_test, boost_pred)))
print("Test r2: " + str(r2_score(y_test, boost_pred)))

Train MSE: 8529319.08823412
Train RMSE: 2920.4998011015373
Train MAE: 2083.8928380018947
Train r2: 0.8364123292185577

Test MSE: 8975853.268164748
Test RMSE: 2995.9728416934536
Test MAE: 2131.7186337427747
Test r2: 0.8283577195042692

In [26]:
### Ada Boosting
ada = AdaBoostRegressor()
ada.fit(X_mat_train, y_train)

ada_train_pred = ada.predict(X_mat_train)
ada_pred = ada.predict(X_mat_test)

print("Train MSE: " + str(mean_squared_error(y_train, ada_train_pred)))
print("Train RMSE: " + str(np.sqrt(mean_squared_error(y_train, ada_train_pred))))
print("Train MAE: " + str(mean_absolute_error(y_train, ada_train_pred)))
print("Train r2: " + str(r2_score(y_train, ada_train_pred)))
print()
print("Test MSE: " + str(mean_squared_error(y_test, ada_pred)))
print("Test RMSE: " + str(np.sqrt(mean_squared_error(y_test, ada_pred))))
print("Test MAE: " + str(mean_absolute_error(y_test, ada_pred)))
print("Test r2: " + str(r2_score(y_test, ada_pred)))

Train MSE: 24964587.63820532
Train RMSE: 4996.45750889621
Train MAE: 4204.04661614821
Train r2: 0.5211928758314619

Test MSE: 25367181.80352125
Test RMSE: 5036.584338966364
Test MAE: 4242.886733847904
Test r2: 0.5149117521841515

In [27]:
### Random Forest
rf = RandomForestRegressor(n_jobs=20)
rf.fit(X_mat_train, y_train)

rf_train_pred = rf.predict(X_mat_train)
rf_pred = rf.predict(X_mat_test)

print("Train MSE: " + str(mean_squared_error(y_train, rf_train_pred)))
print("Train RMSE: " + str(np.sqrt(mean_squared_error(y_train, rf_train_pred))))
print("Train MAE: " + str(mean_absolute_error(y_train, rf_train_pred)))
print("Train r2: " + str(r2_score(y_train, rf_train_pred)))
print()
print("Test MSE: " + str(mean_squared_error(y_test, rf_pred)))
print("Test RMSE: " + str(np.sqrt(mean_squared_error(y_test, rf_pred))))
print("Test MAE: " + str(mean_absolute_error(y_test, rf_pred)))
print("Test r2: " + str(r2_score(y_test, rf_pred)))

/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

Train MSE: 917446.9040279425
Train RMSE: 957.8344867606003
Train MAE: 576.2659862006462
Train r2: 0.9824038706322278

Test MSE: 4931293.282378245
Test RMSE: 2220.651544564848
Test MAE: 1426.486641935005
Test r2: 0.9057005056240471

In [28]:
print(rf.feature_importances_)

[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.64974845e-05
 5.40495663e-05 4.13478297e-05]

In [29]:
### Bagging
bag = BaggingRegressor(n_jobs=20)
bag.fit(X_mat_train, y_train)

bag_train_pred = bag.predict(X_mat_train)
bag_pred = bag.predict(X_mat_test)

print("Train MSE: " + str(mean_squared_error(y_train, bag_train_pred)))
print("Train RMSE: " + str(np.sqrt(mean_squared_error(y_train, bag_train_pred))))
print("Train MAE: " + str(mean_absolute_error(y_train, bag_train_pred)))
print("Train r2: " + str(r2_score(y_train, bag_train_pred)))
print()
print("Test MSE: " + str(mean_squared_error(y_test, bag_pred)))
print("Test RMSE: " + str(np.sqrt(mean_squared_error(y_test, bag_pred))))
print("Test MAE: " + str(mean_absolute_error(y_test, bag_pred)))
print("Test r2: " + str(r2_score(y_test, bag_pred)))

Train MSE: 922464.0827889971
Train RMSE: 960.4499376797299
Train MAE: 575.1578147612156
Train r2: 0.9823076438902189

Test MSE: 4948021.04354014
Test RMSE: 2224.414764278492
Test MAE: 1432.8533402581986
Test r2: 0.9053806261666145

In [30]:
### Grid Search
#https://scikit-learn.org/stable/auto_examples/model_selection/plot_grid_search_digits.html
grid = GridSearchCV(RandomForestRegressor(), cv=10, n_jobs=20, scoring="r2",
            param_grid={})
grid.fit(X_mat_train, y_train)

#print("Best parameters set found on development set:")
#print()
#print(grid.best_params_)
#print()
print("Grid scores on development set:")
print()
means = grid.cv_results_['mean_test_score']
stds = grid.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, grid.cv_results_['params']):
    print("%0.3f (+/-%0.03f) for %r"
        % (mean, std * 2, params))

/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

Grid scores on development set:

0.904 (+/-0.003) for {}

In [33]:
grid_train_pred = grid.predict(X_mat_train)

print()
print("Train MSE: " + str(mean_squared_error(y_train, grid_train_pred)))
print("Train RMSE: " + str(np.sqrt(mean_squared_error(y_train, grid_train_pred))))
print("Train MAE: " + str(mean_absolute_error(y_train, grid_train_pred)))
print("Train r2: " + str(r2_score(y_train, grid_train_pred)))

Train MSE: 909819.6480668479
Train RMSE: 953.8446666343781
Train MAE: 575.2956599277873
Train r2: 0.9825501572260604

In [34]:
grid_pred = grid.predict(X_mat_test)

print()
print("Test MSE: " + str(mean_squared_error(y_test, grid_pred)))
print("Test RMSE: " + str(np.sqrt(mean_squared_error(y_test, grid_pred))))
print("Test MAE: " + str(mean_absolute_error(y_test, grid_pred)))
print("Test r2: " + str(r2_score(y_test, grid_pred)))

Test MSE: 4815819.083083023
Test RMSE: 2194.4974557021073
Test MAE: 1419.9490176584065
Test r2: 0.9079086806368616

In [35]:
importances = rf.feature_importances_

In [36]:
categories = []
for t in enc.categories_:
    for c in t:
        categories.append(c)

In [37]:
for col in X_train.drop(columns=cats).columns:
    categories.append(col)
categories

['ABILENE',
 'ADDISON',
 'ALAMOSA',
 'ALBUQUERQUE',
 'ALEXANDRIA',
 'ALFRED',
 'ALPHARETTA',
 'ALTOONA',
 'ANAHEIM',
 'ANNAPOLIS',
 'ANNISTON',
 'ARLINGTON',
 'ARTESIA',
 'ARVADA',
 'ASHBURN',
 'ASTORIA',
 'ATLANTA',
 'ATLANTIC CITY',
 'AUBURN',
 'AUBURNDALE',
 'AUGUSTA',
 'AURORA',
 'Aberdeen',
 'Abilene',
 'Abington',
 'Ada',
 'Adamsville',
 'Addison',
 'Adelphi',
 'Adrian',
 'Aguadilla',
 'Ahoskie',
 'Aiea',
 'Aiken',
 'Akron',
 'Alameda',
 'Alamogordo',
 'Alamosa',
 'Albany',
 'Albemarle',
 'Albertville',
 'Albion',
 'Albuquerque',
 'Alcorn State',
 'Alexander City',
 'Alexandria',
 'Alfred',
 'Alhambra',
 'Aliso Viejo',
 'Allen Park',
 'Allendale',
 'Allentown',
 'Alliance',
 'Alma',
 'Alpena',
 'Alpine',
 'Altamonte',
 'Altamonte Springs',
 'Alton',
 'Altoona',
 'Altus',
 'Alva',
 'Alvin',
 'Amarillo',
 'Ambler',
 'American Fork',
 'Americus',
 'Ames',
 'Amherst',
 'Amityville',
 'Anaheim',
 'Anchorage',
 'Anderson',
 'Angola',
 'Angwin',
 'Ankeny',
 'Ann Arbor',
 'Annandale',
 'Annandale-On-Hudson',
 'Annapolis',
 'Anniston',
 'Annville',
 'Anoka',
 'Antioch',
 'Apopka',
 'Appleton',
 'Aptos',
 'Arcata',
 'Archbold',
 'Ardmore',
 'Arecibo',
 'Arkadelphia',
 'Arkansas City',
 'Arlington',
 'Arlington Heights',
 'Arnold',
 'Arvada',
 'Ashburn',
 'Asheboro',
 'Asheville',
 'Ashland',
 'Ashtabula',
 'Ashwaubenon',
 'Aston',
 'Astoria',
 'Atchison',
 'Athens',
 'Atherton',
 'Atlanta',
 'Auburn',
 'Auburn Hills',
 'Audubon',
 'Augusta',
 'Aurora',
 'Austin',
 'Austintown',
 'Ave Maria',
 'Avon Park',
 'Avondale',
 'Azusa',
 'BALTIMORE',
 'BANGOR',
 'BAY CITY',
 'BAYAMON',
 'BEATRICE',
 'BILLINGS',
 'BISMARCK',
 'BLAIRSVILLE',
 'BLOOMINGTON',
 'BOCA RATON',
 'BOISE',
 'BOONVILLE',
 'BOSTON',
 'BREA',
 'BRENTWOOD',
 'BRICK',
 'BRIGHTON',
 'BROCKTON',
 'BRONX',
 'BROOKLYN',
 'BROWNWOOD',
 'BUFFALO',
 'BULLHEAD CITY',
 'BURLINGTON',
 'Babson Park',
 'Bad Axe',
 'Bainbridge',
 'Bakersfield',
 'Baldwin City',
 'Ballston Spa',
 'Baltimore',
 'Bangor',
 'Banner Elk',
 'Bar Harbor',
 'Baraboo',
 'Barbourville',
 'Barnesville',
 'Barranquitas',
 'Bartlesville',
 'Batavia',
 'Batesville',
 'Baton Rouge',
 'Battle Creek',
 'Bay City',
 'Bay Minette',
 'Bayamon',
 'Bayamón',
 'Bayside',
 'Baytown',
 'Beachwood',
 'Bear',
 'Beaufort',
 'Beaumont',
 'Beaver',
 'Beaver Falls',
 'Beavercreek',
 'Beaverton',
 'Beckley',
 'Bedford',
 'Bedford Park',
 'Beebe',
 'Beeville',
 'Bel Air',
 'Bell',
 'Bellefontaine',
 'Belleview',
 'Belleville',
 'Bellevue',
 'Bellingham',
 'Belmont',
 'Beloit',
 'Belton',
 'Beltsville',
 'Bemidji',
 'Benbrook',
 'Bend',
 'Bennington',
 'Bensalem',
 'Benton Harbor',
 'Bentonville',
 'Berea',
 'Berkeley',
 'Berlin',
 'Berrien Springs',
 'Bessemer',
 'Bethany',
 'Bethesda',
 'Bethlehem',
 'Bettendorf',
 'Beverly',
 'Beverly Hills',
 'Biddeford',
 'Big Rapids',
 'Big Spring',
 'Billerica',
 'Billings',
 'Biloxi',
 'Binghamton',
 'Birmingham',
 'Bismarck',
 'Blacksburg',
 'Blackwood',
 'Blaine',
 'Blair',
 'Blairsville',
 'Bloomfield',
 'Bloomfield Hills',
 'Bloomingdale',
 'Bloomington',
 'Bloomsburg',
 'Blountville',
 'Blue Ash',
 'Blue Bell',
 'Blue Island',
 'Blue Mountain',
 'Blue Springs',
 'Bluefield',
 'Bluffton',
 'Blytheville',
 'Boardman',
 'Boaz',
 'Boca Raton',
 'Bohemia',
 'Boiling Springs',
 'Boise',
 'Bolivar',
 'Bonita Springs',
 'Boone',
 'Booneville',
 'Boonville',
 'Bordentown',
 'Borger',
 'Bossier City',
 'Boston',
 'Bothell',
 'Bottineau',
 'Boulder',
 'Bourbonnais',
 'Bourne',
 'Bowie',
 'Bowling Green',
 'Boynton Beach',
 'Bozeman',
 'Bradenton',
 'Bradford',
 'Brainerd',
 'Braintree',
 'Branchburg',
 'Branford',
 'Brattleboro',
 'Brecksville',
 'Bremerton',
 'Brenham',
 'Brentwood',
 'Brevard',
 'Brick',
 'Bridgeport',
 'Bridgeton',
 'Bridgeview',
 'Bridgewater',
 'Bridgton',
 'Brighton',
 'Bristol',
 'Broadview Heights',
 'Brockport',
 'Brockton',
 'Broken Arrow',
 'Bronx',
 'Bronxville',
 'Brookfield',
 'Brookings',
 'Brookline',
 'Brooklyn',
 'Brooklyn Center',
 'Brooklyn Heights',
 'Brooklyn Park',
 'Brookville',
 'Broomall',
 'Broomfield',
 'Brownsburg',
 'Brownsville',
 'Brownwood',
 'Brunswick',
 'Bryan',
 'Bryn Athyn',
 'Bryn Mawr',
 'Buckhannon',
 'Buena Vista',
 'Buffalo',
 'Buies Creek',
 'Burbank',
 'Burley',
 'Burlington',
 'Burns Flat',
 'Burnsville',
 'Burr Ridge',
 'Burton',
 'Butler',
 'Butte',
 'Buzzards Bay',
 'CAMBRIDGE',
 'CAMP HILL',
 'CANAL WINCHESTER',
 'CAPE GIRARDEAU',
 'CARLSBAD',
 'CARO',
 'CATONSVILLE',
 'CENTERVILLE',
 'CHAMBERSBURG',
 'CHARLEROI',
 'CHARLOTTE',
 'CHATTANOOGA',
 'CHERRY HILL',
 'CHESAPEAKE',
 'CHESTER',
 'CHESTERFIELD',
 'CHICAGO',
 'CHICOPEE',
 'CINCINNATI',
 'CLEARFIELD',
 'CLEVELAND',
 'CLEVELAND HEIGHTS',
 'CLIFTON',
 'COLORADO SPRINGS',
 'COLUMBIA HEIGHTS',
 'COLUMBUS',
 'CONCORD',
 'CONWAY',
 'CRAWFORDSVILLE',
 'Cable',
 'Cadillac',
 'Caguas',
 'Calais',
 'Caldwell',
 'Calexico',
 'California',
 'Calmar',
 'Calumet City',
 'Camarillo',
 'Cambridge',
 'Camden',
 'Campbell',
 'Campbellsville',
 'Canal Winchester',
 'Canandaigua',
 'Canfield',
 'Canoga Park',
 'Canonsburg',
 'Canton',
 'Canyon',
 'Canyon Country',
 'Cape Girardeau',
 'Carbondale',
 'Cardiff',
 'Caribou',
 'Carlinville',
 'Carlisle',
 'Carlsbad',
 'Carneys Point',
 'Caro',
 'Carolina',
 'Carpinteria',
 'Carrollton',
 'Carson',
 'Carson City',
 'Carterville',
 'Carthage',
 'Cary',
 'Casa Grande',
 'Casper',
 'Casselberry',
 'Castine',
 'Castleton',
 'Castro Valley',
 'Cathedral City',
 'Cayey',
 'Cazenovia',
 'Cedar City',
 'Cedar Falls',
 'Cedar Hill',
 'Cedar Rapids',
 'Cedarville',
 'Celina',
 'Centennial',
 'Center Valley',
 'Centerville',
 'Central',
 'Central Islip',
 'Centralia',
 'Centreville',
 'Cerritos',
 'Chadron',
 'Chalmette',
 'Chambersburg',
 'Chamblee',
 'Champaign',
 'Chandler',
 'Chantilly',
 'Chanute',
 'Chapel Hill',
 'Charles Town',
 'Charleston',
 'Charlestown',
 'Charlotte',
 'Charlotte Amalie',
 'Charlottesville',
 'Charlston',
 'Chattanooga',
 'Cheektowaga',
 'Chelsea',
 'Cheney',
 'Cherry Hill',
 'Chesapeake',
 'Chester',
 'Chesterfield',
 'Chestertown',
 'Chestnut Hill',
 'Cheyenne',
 'Cheyney',
 'Chicago',
 'Chicago Heights',
 'Chickasha',
 'Chico',
 'Chicopee',
 'Chillicothe',
 'Christiansburg',
 'Chubbuck',
 'Chula Vista',
 'Cicero',
 'Cincinnati',
 'Circleville',
 'Cisco',
 'Citrus Heights',
 'City of Industry',
 'Claremont',
 'Claremore',
 'Clarendon',
 'Clarion',
 'Clarkesville',
 'Clarksburg',
 'Clarkston',
 'Clarksville',
 'Clawson',
 'Clayton',
 'Clearfield',
 'Clearwater',
 'Clemson',
 'Cleveland',
 'Cleveland Heights',
 'Clifton',
 'Clifton Forge',
 'Clinton',
 'Clinton Township',
 'Clive',
 'Cloquet',
 'Clovis',
 'Clyde',
 'Coachella',
 'Coalinga',
 'Coatesville',
 'Cobleskill',
 'Cochran',
 'Cocoa',
 "Coeur D'Alene",
 "Coeur d'Alene",
 'Coffeyville',
 'Colby',
 'Colchester',
 'Coldwater',
 'College Park',
 'College Place',
 'College Station',
 'Collegedale',
 'Collegeville',
 'Collinsville',
 'Colonial Heights',
 'Colorado Springs',
 'Colton',
 'Columbia',
 'Columbus',
 'Commerce',
 'Compton',
 'Conception',
 'Concord',
 'Concord Twp',
 'Concordia',
 'Conroe',
 'Conway',
 'Conyers',
 'Cookeville',
 'Coolidge',
 'Coon Rapids',
 'Coos Bay',
 'Copley',
 'Coral Gables',
 'Coral Springs',
 'Cordova',
 'Corinth',
 'Corning',
 'Corona',
 'Corpus Christi',
 'Corsicana',
 'Cortland',
 'Corvallis',
 'Costa Mesa',
 'Cottleville',
 'Council Bluffs',
 'Covington',
 'Craftsbury Common',
 'Cranberry Township',
 'Cranford',
 'Cranston',
 'Crawfordsville',
 'Cresson',
 'Creston',
 'Crestview Hills',
 'Crestwood',
 'Crete',
 'Cromwell',
 'Crookston',
 'Cross Lanes',
 'Crossett',
 'Crossville',
 'Crystal Lake',
 'Cullowhee',
 'Culpeper',
 'Culver City',
 'Cumberland',
 'Cupertino',
 'Curtis',
 'Cuthbert',
 'Cutler Bay',
 'Cuyahoga Falls',
 'Cypress',
 'DALLAS',
 'DANVILLE',
 'DAVENPORT',
 'DAYTON',
 'DAYTONA BEACH',
 'DEARBORN',
 'DELRAY BEACH',
 'DENTON',
 'DENVER',
 'DES MOINES',
 'DETROIT',
 'DETROIT LAKES',
 'DOVER',
 'DUNCANVILLE',
 'DUNDALK',
 'Dagsboro',
 'Dahlonega',
 'Dallas',
 'Dalton',
 'Danbury',
 'Danvers',
 'Danville',
 'Daphne',
 'Darien',
 'Davenport',
 'Davidson',
 'Davie',
 'Davis',
 'Davison',
 'Dawsonville',
 'Dayton',
 'Daytona Beach',
 'De Pere',
 'DeLand',
 'DeSoto',
 'Dearborn',
 'Decatur',
 'Decorah',
 'Deerfield',
 'Defiance',
 'Dekalb',
 'Del Rio',
 'Deland',
 'Delano',
 'Delaware',
 'Delhi',
 'Delran',
 'Delray Beach',
 'Delta',
 'Demorest',
 'Denham Springs',
 'Denison',
 'Denmark',
 'Denton',
 'Denver',
 'Des Moines',
 'Des Plaines',
 'Detroit',
 'Detroit Lakes',
 'Devils Lake',
 'Dickinson',
 'Dickson City',
 'Dillon',
 'Dimondale',
 'Dix Hills',
 'Dixon',
 'Dobbs Ferry',
 'Dobson',
 'Dodge City',
 'Donaldson',
 'Doral',
 'Dorchester',
 'Dothan',
 'Douglas',
 'Douglasville',
 'Dover',
 'Dowagiac',
 'Downers Grove',
 'Downey',
 'Downington',
 'Downingtown',
 'Doylestown',
 'Draper',
 'Dryden',
 'Du Bois',
 'DuBois',
 'Dublin',
 'Dubuque',
 'Dudley',
 'Due West',
 'Duluth',
 'Dunbar',
 'Duncanville',
 'Dunmore',
 'Dunwoody',
 'Durango',
 'Durant',
 'Durham',
 'Dyersburg',
 'EAST GRAND FORKS',
 'EASTON',
 'EDGEWOOD',
 'EDINA',
 'EDINBURG',
 'EL PASO',
 'ELIZABETH',
 'ENFIELD',
 'ERIAL',
 'ERIE',
 'Eagan',
 'Eagle Butte',
 'Eagle Pass',
 'Earth City',
 'East Grand Forks',
 'East Greenwich',
 'East Hartford',
 'East Lansing',
 'East Liverpool',
 'East Moline',
 'East Orange',
 'East Peoria',
 'East Point',
 'East Providence',
 'East Stroudsburg',
 'East Windsor',
 'Eastlake',
 'Eastman',
 'Easton',
 'Eau Claire',
 'Eden Prairie',
 'Edina',
 'Edinboro',
 'Edinburg',
 'Edison',
 'Edmond',
 'Edwardsville',
 'Egg Harbor Township',
 'El Cajon',
 'El Centro',
 'El Dorado',
 'El Dorado Hills',
 'El Monte',
 'El Paso',
 'El Reno',
 'Eldon',
 'Elgin',
 'Elizabeth',
 'Elizabeth City',
 'Elizabethtown',
 'Elk River',
 'Elkhart',
 'Elkins',
 'Elkins Park',
 'Elko',
 'Ellendale',
 'Ellensburg',
 'Ellisville',
 'Ellsworth Air Force Base',
 'Elmhurst',
 'Elmira',
 'Elmsford',
 'Elon',
 'Ely',
 'Elyria',
 'Emeryville',
 'Emmitsburg',
 'Emory',
 'Emporia',
 'Encino',
 'Enfield',
 'Englewood',
 'Enid',
 'Ennis',
 'Enterprise',
 'Eolia',
 'Ephraim',
 'Epworth',
 'Erdenheim',
 'Erie',
 'Erlanger',
 'Escanaba',
 'Escondido',
 'Espanola',
 'Essex Junction',
 'Essington',
 'Estherville',
 'Eugene',
 'Eunice',
 'Eureka',
 'Evans',
 'Evanston',
 'Evansville',
 'Eveleth',
 'Everett',
 'Ewing',
 'Exton',
 'FAIRFIELD',
 'FAIRHOPE',
 'FAIRLESS HILLS',
 'FAIRMONT',
 'FALLS CHURCH',
 'FARIBAULT',
 'FARMINGTON HILLS',
 'FEDERAL WAY',
 'FESTUS',
 'FIFE',
 'FINDLAY',
 'FLINT',
 'FREDERICK',
 'FREDERICKSBURG',
 'FREMONT',
 'FRENCH CAMP',
 'FT MYERS',
 'FT WAYNE',
 'Fairbanks',
 'Fairborn',
 'Fairburn',
 'Fairfax',
 'Fairfield',
 'Fairmont',
 'Fairview Heights',
 'Fairview Park',
 'Fajardo',
 'Fall River',
 'Falls Church',
 'Falls Creek',
 'Falmouth',
 'Fargo',
 'Faribault',
 'Farmers Branch',
 'Farmingdale',
 'Farmington',
 'Farmington Hills',
 'Farmville',
 'Fayette',
 'Fayetteville',
 'Feasterville',
 'Federal Way',
 'Fennimore',
 'Fenton',
 'Fergus Falls',
 'Fern Park',
 'Ferrum',
 'Fife',
 'Findlay',
 'Fitchburg',
 'Flagstaff',
 'Flat Rock',
 'Flint',
 'Florence',
 'Florissant',
 'Flowood',
 'Flushing',
 'Foley',
 'Folsom',
 'Fond Du Lac',
 'Fond du Lac',
 'Fontana',
 'Ford City',
 'Forest City',
 'Forest Grove',
 'Forest Hills',
 'Forest Park',
 'Forrest City',
 'Fort  Morgan',
 'Fort  Worth',
 'Fort Collins',
 'Fort Dodge',
 'Fort Kent',
 'Fort Lauderdale',
 'Fort Mitchell',
 'Fort Mohave',
 'Fort Myers',
 'Fort Pierce',
 'Fort Scott',
 'Fort Smith',
 'Fort Valley',
 'Fort Washington',
 'Fort Wayne',
 'Fort Worth',
 'Forty Fort',
 'Fountain Valley',
 'Frackville',
 'Framingham',
 'Frankfort',
 'Franklin',
 'Franklin Springs',
 'Frederick',
 'Fredericksburg',
 'Fredonia',
 'Freehold',
 'Freemont',
 'Freeport',
 'Fremont',
 'French Camp',
 'Fresh Meadows',
 'Fresno',
 'Friendswood',
 'Frostburg',
 'Ft Benning',
 'Ft Myers',
 'Ft Smith',
 'Ft Worth',
 'Ft. Drum',
 'Ft. Smith',
 'Ft. Washington',
 'Ft. Wayne',
 'Fullerton',
 'Fulton',
 'GARLAND',
 'GERMANTOWN',
 'GLEN ALLEN',
 'GLEN BURNIE',
 'GRAND ISLAND',
 'GRAND RAPIDS',
 'GRANDVIEW',
 'GRANGER',
 'GRANTS PASS',
 'GRAPEVINE',
 'GREAT FALLS',
 'GREENFIELD',
 'GREENSBURG',
 'GREENWICH',
 'GREENWOOD',
 'GUAYAMA',
 'GULFPORT',
 'GURABO',
 'Gaffney',
 'Gainesville',
 'Gaithersburg',
 'Galesburg',
 'Gallatin',
 'Gallipolis',
 'Galloway',
 'Gallup',
 'Galveston',
 'Gambier',
 'Garden City',
 'Garden Grove',
 'Gardena',
 'Gardner',
 'Garland',
 'Gary',
 'Gastonia',
 'Geneseo',
 'Geneva',
 'Georgetown',
 'Gettysburg',
 'Getzville',
 'Gilroy',
 'Gladstone',
 'Glasgow',
 'Glassboro',
 'Glen Allen',
 'Glen Ellyn',
 'Glendale',
 'Glendale Heights',
 'Glendive',
 'Glendora',
 'Glens Falls',
 'Glenside',
 'Glenville',
 'Glenwood Springs',
 'Gloucester',
 'Godfrey',
 'Gold River',
 'Golden',
 'Goldsboro',
 'Gonzales',
 'Goodland',
 'Goodman',
 'Goodwell',
 'Goose Creek',
 'Goshen',
 'Graceville',
 'Grafton',
 'Grambling',
 'Granada Hills',
 'Grand Blanc',
 'Grand Chute',
 'Grand Forks',
 'Grand Island',
 'Grand Junction',
 'Grand Prairie',
 'Grand Rapids',
 'Granger',
 'Granite Falls',
 'Graniteville',
 'Grants',
 'Grants Pass',
 'Granville',
 'Grayslake',
 'Grayson',
 'Great Barrington',
 'Great Bend',
 'Great Falls',
 'Greeley',
 'Green Bay',
 'Greenacres',
 'Greencastle',
 'Greeneville',
 'Greenfield',
 'Greensboro',
 'Greensburg',
 'Greenville',
 'Greenwood',
 'Greenwood Village',
 'Grenada',
 'Gresham',
 'Gretna',
 'Griffin',
 'Grinnell',
 'Groton',
 'Grove City',
 'Groveport',
 'Guayama',
 'Guaynabo',
 'Gulfport',
 'Gunnison',
 'Gurabo',
 'Gwynedd Valley',
 'HAMPTON',
 'HARLINGEN',
 'HARRISONBURG',
 'HARTFORD',
 'HASKELL',
 'HASTINGS',
 'HATHORNE',
 'HATTIESBURG',
 'HAVERHILL',
 'HAYWARD',
 'HAZARD',
 'HIGH POINT',
 'HOLLAND',
 'HOLLYWOOD',
 'HOLYOKE',
 'HORNELL',
 'HOUSTON',
 'HOWELL',
 'HUNTINGTON PARK',
 'HURON',
 'HURST',
 'HUTCHINSON',
 'Hackensack',
 'Hackettstown',
 'Hagerstown',
 ...]

In [38]:
coefs = pd.SparseDataFrame(np.array(categories).reshape(1,-1), columns=importances)
coefs

/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  """Entry point for launching an IPython kernel.
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3456: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return klass(values, index=self.index, name=items, fastpath=True)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/sparse/frame.py:745: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  default_fill_value=self._default_fill_value,
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5997: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(data).__finalize__(self)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:392: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return cls(data, **kwargs)

,0.000000e+00,0.000000e+00,0.000000e+00,2.998279e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.020306e-13,0.000000e+00,...,1.751852e-05,8.500069e-05,2.499931e-05,2.750488e-05,1.622961e-04,1.267613e-04,2.164662e-05,1.649748e-05,5.404957e-05,4.134783e-05
0,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,ALBUQUERQUE,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,ANAHEIM,NOPELL_UNKN_2YR_TRANS_YR8_RT,...,OMAWDP8_NOTFIRSTTIME,OMENRUP_NOTFIRSTTIME,OMENRYP_FULLTIME,OMENRAP_FULLTIME,OMAWDP8_FULLTIME,OMENRUP_FULLTIME,OMENRYP_PARTTIME,OMENRAP_PARTTIME,OMAWDP8_PARTTIME,OMENRUP_PARTTIME

In [39]:
coefs.sort_index(axis=1, inplace=True)
coefs

/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3456: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return klass(values, index=self.index, name=items, fastpath=True)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/sparse/frame.py:745: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  default_fill_value=self._default_fill_value,
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5997: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(data).__finalize__(self)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:392: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return cls(data, **kwargs)

,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.011214,0.011566,0.012977,0.015056,0.016332,0.018669,0.020258,0.037933,0.063083,0.412549
0,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,...,UNKN_ORIG_YR2_RT,TUITFTE,LO_INC_WDRAW_ORIG_YR2_RT,TUITIONFEE_PROG,UNKN_ORIG_YR3_RT,0.005240699905495576,TUITIONFEE_IN,D_PCTPELL_PCTFLOAN,D150_4_HISP,1.0

In [40]:
least = coefs.iloc[:,:10]
least

/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3456: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return klass(values, index=self.index, name=items, fastpath=True)

,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT,NOPELL_UNKN_2YR_TRANS_YR8_RT

In [41]:
most = coefs.iloc[:,-10:]
most

/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/sparse/frame.py:745: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  default_fill_value=self._default_fill_value,
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5997: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(data).__finalize__(self)
/Users/Mattdintino/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3456: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return klass(values, index=self.index, name=items, fastpath=True)

,0.011214,0.011566,0.012977,0.015056,0.016332,0.018669,0.020258,0.037933,0.063083,0.412549
0,UNKN_ORIG_YR2_RT,TUITFTE,LO_INC_WDRAW_ORIG_YR2_RT,TUITIONFEE_PROG,UNKN_ORIG_YR3_RT,0.005240699905495576,TUITIONFEE_IN,D_PCTPELL_PCTFLOAN,D150_4_HISP,1.0